### ISSUE TITLE
Loading higlass failure

### ISSUE THREAD

**Issue by xinyangbing** [higlass/higlass#1001]
_Commit_: 

#### Steps to reproduce
1.Simply loading website leads to failure to load. No common data is available in own server either. 

#### Observed behavior
- 
<img width="1280" alt="Screen Shot 2020-12-14 at 11 30 59 AM" src="https://user-images.githubusercontent.com/55600546/102107954-51e7cd00-3e00-11eb-8f89-e4fb62c88022.png">

#### Expected behavior
-

**Comment by alexander-veit** [comment]
Thanks for reporting. The Higlass server was down this morning. It should work again now.

**Comment by flekschas** [comment]
Seems to be solved. Please reopen if this is still an issue
