### ISSUE TITLE
Color code for color map

### ISSUE THREAD

**Issue by yancychy** [higlass/higlass#1014]
Hi, I find the RdYlBu_r colormap is better to view Hi-C ICE data in hicexplorer. But in higlass, there is only jet colormap may close to RdYlBu_r. 
Is it possible to add more color code or at least RdYlBu_r into the color map? Thanks.  https://matplotlib.org/2.0.2/examples/color/colormaps_reference.html

**Comment by pkerpedjiev** [comment]
You can edit viewconf to define a custom color scheme. See here: https://docs.higlass.io/track_types.html#options

To edit the viewconf, you have to select "Edit view config" from the view config menu: 

![image](https://user-images.githubusercontent.com/2143629/109458495-c0a4f180-7a11-11eb-888c-df9fe185513a.png)

If you wanted to have it as an option in the track config menu you could submit a PR to add it here: https://github.com/higlass/higlass/blob/f954ba2ae2f0062e8d450e726d8a0e64bff75f12/app/scripts/configs/options-info.js#L662

**Comment by yancychy** [comment]
Ok. Thank. When I edit the viewconf and save, the page is broke down.  I guess it is my version problem. 
The difference between my version and http://higlass.io/version.txt  is SERVER_VERSION: 1.14.2 used in my version.

**Comment by pkerpedjiev** [comment]
Hmm, that's odd. The server version shouldn't matter. Editing the viewconf is a client only configuration. Perhaps it wasn't a valid JSON? Could you post a screenshot of the developer console when the page crashes? You can find that in the Google menu -> More tools -> Developer tools and then clicking on the "Console" tab.

**Comment by yancychy** [comment]
Yes. It's JSON probelm. The console logs are follows:

cb2fb4b8-9f74-4cbd-8ee7-f60b61e765e6:1 HiGlass v1.11.4: http://higlass.io
hglib.min.js:88 Invalid viewconf
(anonymous) @ hglib.min.js:88
hglib.min.js:88 [
  {
    "keyword": "additionalProperties",
    "dataPath": ".views[0].layout",
    "schemaPath": "#/definitions/viewProperties/layout/additionalProperties",
    "params": {
      "additionalProperty": "moved"
    },
    "message": "should NOT have additional properties"
  }
]
(anonymous) @ hglib.min.js:88
DevTools failed to load SourceMap: Could not parse content for http://localhost:8989/pixi-legacy.min.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for http://localhost:8989/autotrack.custom.js.map: Unexpected token < in JSON at position 0

**Comment by pkerpedjiev** [comment]
This sounds like it's resolved? I'm going to close it for now. Feel free to reopen if it's still an issue.
