### ISSUE TITLE
The ICE normalization in Higlass and Hicexplorer are differnt

### ISSUE THREAD

**Issue by yancychy** [higlass/higlass#1016]
_Commit_: 
 The ICE normalization in Higlass and Hicexplore are differnt. 
https://drive.google.com/file/d/1Wm-wPGM7JQrrNistgKbMfPUJZ_khcL5s/view?usp=sharing 
#### Steps to reproduce
1. I apply Hicexplorer to normalize Hi-C data with ICE.
2. Use cooler zoomify --nproc 8  mock_ICE.cool to get the mcool files.
3. Higlass is used to visualize the Hi-C data. (Tranform to ICE and value scaling are log)
4. I used Hicexplorer https://hicexplorer.readthedocs.io/en/latest/content/tools/hicPlotMatrix.html to draw a region chr3L:18900000-19050000. 
5. hicPlotMatrix -m mock_ICE.cool --outFileName mock_ICE.png --region chr3L:18900000-19050000 --dpi 600 --log1p
#### Observed behavior
- I checked the region in chr3L:18900000-19050000. The higlass and hicepxplorer visualization are different. There are two blue blanks around 19,000,000 in higlass but only 1 in Hicexplorer. 

#### Expected behavior
- With same ICE normalization, the plot should be same or similar. Hicexplorer used log1p to scale the values and higlass use log to scale the values. Is it the reason? Thanks.

**Comment by pkerpedjiev** [comment]
Hmm, maybe @nvictus has thoughts?

**Comment by golobor** [comment]
Hi, I have no solution, but these two regions look clearly different to me - that is if  they are coming from different maps or different regions of a map...

**Comment by yancychy** [comment]
Thanks. I used cool file in Hicexplorer and mcool in Higlass. mcool is tranformed from the cool file.
Dose higlass re-do ICE normalization on the mcool file or just use the ICE data in the mcool?

**Comment by pkerpedjiev** [comment]
HiGlass uses the ICE normalization in the file. One other thing that could
be happening is that the chromosome ordering could be inconsistent between
the cooler file and the chromosome labels track.

Is the cooler file that you’re looking at public? If not could you check
the chromosome order in the file (there should be docs for that on the
cooler docs page) and see if it matches the order in the labels track in
higlass?

**Comment by yancychy** [comment]
Thanks. It's not public. But I really find that the Hi-C order is not consistent to label track. The Hi-C order is from chr3R, chr3L, chr2R, chrX, chr2L, chrY, chr4, chrM. But the label track is from chr2L to chrM.

**Comment by yancychy** [comment]
I ordered the chromosomes in the cool file from chr2L to chrM. But when loading the mcool file into Higlass, it automatically order s the chromosomes by size from chr3R to chrM. Hence, the Hi-C data is not consistent to the chromsomes. Could Higlass do a normal order on the Hi-C data? When loading the chromosom label track, they are ordered from chr2L to chrM.

**Comment by pkerpedjiev** [comment]
HiGlass will load the cooler file with the order of the chromosomes that's stored in it. You have to make sure that your chromsizes track contains the same order. One option would be to change the order of your chromsizes track to be largest to smallest. Otherwise you'll have to reorder the cool file.

Not sure if that helps. Let me know if I should try to rephrase that. Also, what's the command that you use to ingest the cooler file?

**Comment by yancychy** [comment]
Thanks. It's work now. I restart higlass server. The error is caused by cashe in the browser. After restarting, the Hi-C order is normal from chr2L to chrM.

**Comment by pkerpedjiev** [comment]
Awesome, glad to hear it's resolved!
