### ISSUE TITLE
http://higlass.io/ data does not load and neither it does in local instances.

### ISSUE THREAD

**Issue by iagooteroc** [higlass/higlass#1022]
_Commit_: 923ed43a08aa8d3ffbb0e1569bf55c5de37f1fef

#### Steps to reproduce
1. Open http://higlass.io/ or start a local instance and open it in browser.

#### Observed behavior
- http://higlass.io/ is not loading and I can't navigate between positions on the local instance as hg19 is not loading, nor the available online data.

#### Expected behavior
- http://higlass.io/ should be operational and hg19 and available online data should load on the local instance.

I would post this on the Slack channel but the invitation is not working and I don't have a @harvard.edu email.

**Comment by sehilyi** [comment]
Sorry for the inconvenience. I just restarted the server and it should work.

Btw, we recently fixed the invitation link for the Slack channel, so I think you should be able to join the slack channel with any email address.

[![Slack](https://img.shields.io/badge/join-Slack-red.svg?colorB=ff4000)](https://join.slack.com/t/higlass/shared_invite/zt-nv5h5hsi-tjM9ydx0EH3Svn4jx~tveQ)

**Comment by iagooteroc** [comment]
It works now and I was able to join. Thank you vey much.
