### ISSUE TITLE
How can I get an invitation to the slack channel so I can ask questions there?

### ISSUE THREAD

**Issue by rsharris** [higlass/higlass#1056]
_Commit_: 

#### Steps to reproduce
1. go to https://higlass.io/about
2. scroll down the page to the list of contacts
3. by "General" click on "Slack"
4. try to "Start by entering the email address you use for work"
5. it seems only @harvard.edu email addresses are allowed
6. notice the small print "Don’t have an @harvard.edu email address? Contact the workspace administrator at HiGlass for an invitation."
7. click on "contact us" at the very bottom of the page.
8. try to sign in with your already-existing slack email address and password (good luck)

#### Observed behavior
- It seems that you have to ALREADY have been invited to join the HiGlass slack worskspace to be able to sign in at this page. Please correct me if I am wrong.

#### Expected behavior
(A) Considering that this is listed as the "general" contact point for HiGlass, it would seem like it ought to lead you to a way to ask general questions.
(B) At step 6 the user is told to "the workspace administrator at HiGlass" but isn't given any means to do so. Clicking on that instruction does nothing. The "contact us" link at the bottom of the page is the only other option that appears relevant, but it seems you already have to have your foot in the door before you are allowed to knock. 

Before posting this it was suggested I check out the posting guidelines. That took me to
https://github.com/higlass/higlass/blob/a143984528abd8383da5a59b87932c58904c8027/CONTRIBUTING.md
which under "Help! I am lost" says "Join our Slack channel and we're happy to help." Seems promising. But that just took me to
404: NOT_FOUND
Code: DEPLOYMENT_NOT_FOUND
ID: iad1::4c6nt-1632771336302-39dd73da97b7

Further down the posting guidelines page I see "Community: https://higlass.slack.com Join Now!" but that just takes me back to the same locked door described earlier.

**Comment by pkerpedjiev** [comment]
Sorry, Slack doesn't let us have an open invite to any email address. Even trying to enter a general one like gmail.com is rejected:

![image](https://user-images.githubusercontent.com/2143629/134975287-e55ed094-66f5-4cd6-a937-87ff5248576e.png)

If you send me (pkerpedjiev@gmail.com) your email address, I'll be happy to send you an invite.

There used to be a service that would auto-generate an invite for any email address but it was discontinued at some point. If you know of a way to create a perma-invite on Slack, we would be happy to use it. The `@harvard.edu` email address is there because that's where the HiGlass project originated.

**Comment by flekschas** [comment]
@rsharris Try https://join.slack.com/t/higlass/shared_invite/zt-nv5h5hsi-tjM9ydx0EH3Svn4jx~tveQ
That's the link from your github repo. It should allow any email address.

**Comment by flekschas** [comment]
Glad to hear it worked! 🎉 Welcome to our Slack community. The link is from the [Slack badge on the main repo](https://github.com/higlass/higlass#readme) (the orange button on the right)

![Screen Shot 2021-09-27 at 9 07 12 PM](https://user-images.githubusercontent.com/932103/135005756-cefca083-56db-4bab-8aef-dafcf455e7b1.png)

We really need to update the docker image at some point to get rid of the dead link haha.
