### ISSUE TITLE
Gene annotations from Ensembl models

### ISSUE THREAD

**Issue by ChristopherBarrington** [higlass/higlass#1059]
I have the Docker image 0.8.7 and `versions.txt` contains:

```
SERVER_VERSION: 1.14.2
WEB_APP_VERSION: 1.1.11
``` 

I have mcool files that were aligned against cerevisiae R64-1-1. I have a BED file of gene annotations - because it is yeast it has only one exon per gene (see below).

```
# head /ingest/higlass/annotations/S288C.bed
I	334	649	YAL069W_mRNA	0	+	334	649	0	1	315,	0,
I	537	792	YAL068W-A_mRNA	0	+	537	792	0	1	255,	0,
I	1806	2169	YAL068C_mRNA	0	-	1806	2169	0	1	363,	0,
I	2479	2707	YAL067W-A_mRNA	0	+	2479	2707	0	1	228,	0,
I	7234	9016	YAL067C_mRNA	0	-	7234	9016	0	1	1782,	0,
```

I have been trying and failing to make this file into a gene annotations track. I have tried to use the guide for adding gene annotations but I couldn't get that working for the SacCer example (the gzip files wold not extract) but I think some of the steps in that guide a redundant in my case. So I think I can convert the BED file to BEDDB and ingest that into my HiGlass docker container.

I have been going round in circles and just cannot figure out how I can import this data into the container - I have already got the mcool matrices and chromsizes imported and working just great. But this is driving me mad!

#### Steps to reproduce
1. `clodius aggregate bedfile --chromsizes-filename ../chromsizes-tsv/S288C.chromsizes S288C.bed`
2. `python higlass-server/manage.py ingest_tileset --filename /ingest/higlass/annotations/S288C.bed.beddb --coordSystem S288C --coordSystem2 S288C --name 'S288C' --project-name Annotations --filetype beddb`

#### Observed behavior
- The track does not get listed in the menu

#### Expected behavior
- I would like to be able to plot the gene models from the attached BED file [S288C.bed.txt](https://github.com/higlass/higlass/files/7331204/S288C.bed.txt)

Thank you for your time and help

**Comment by pkerpedjiev** [comment]
I used the chromsizes here: https://www.yeastgenome.org/strain/s288c

And then ran:

```
wget -NP data https://github.com/higlass/higlass/files/7331204/S288C.bed.txt

awk '{ print $1 "\t" $2 "\t" $3 "\t" $4 "\t0\t" $6 "\t" $4 "\t" $4 "\t" "-" "\t" "-" "\t" $2 "\t" $3 "\t" $2 "\t" $3 }' data/S288C.bed.txt > data/S288C.hgbed

clodius aggregate bedfile --chromsizes-filename data/S288C_contigs.txt  data/S288C.hgbed
```

Here's a preview of what the gene annotations look like. You'll see the commands I used to generate it associated with the dataset:

https://resgen.io/pete/S288C/project/RR_w7s2pSoCg7c9GqLMSPA

If you want better persistence of the labels, you can assign values to the "score" field (the fifth column). There's a description of the fields in the `.hgbed` file here: https://github.com/higlass/gene_annotations#expected-format (it's also in the higlass docs but [it's buried at the end of a long code snippet](https://docs.higlass.io/data_preparation.html#get-full-model-and-citation-count-for-each-gene)).

Hope this helps. I'm going to close this issue but please feel free to add comments if this doesn't work for you.

**Comment by ChristopherBarrington** [comment]
Thank you for your time. The pointers to file format will be very useful; I had read that section but did get a bit overwhelmed I have to admit.

I have followed the above to make the `beddb` file and tried to ingest it as a `gene-annotations` datatype - like your screenshot.

```
$ md5sum /ingest/higlass/annotations/S288C.hgbed*
4a41e32a5375143651aff6ccff46fe96  /ingest/higlass/annotations/S288C.hgbed
080ac95f24880461424bced7d65474ae  /ingest/higlass/annotations/S288C.hgbed.beddb
$
```

It is listed as a tileset after ingest but does not appear in the list of tracks ...?

```
$ higlass list_tilesets
tileset: Tileset [name: Chromosomes (BY4742)] [ft: chromsizes-tsv] [uuid: RxHwI16wRfWVbI7n1JdrqA]
tileset: Tileset [name: Chromosomes (S288C)] [ft: chromsizes-tsv] [uuid: cc5_AipXQwaJj_ERs_c-iw]
tileset: Tileset [name: A364] [ft: cooler] [uuid: JD9UGPOxQ5uNEo99ETop9g]
$
$ higlass ingest_tileset --filename /ingest/higlass/annotations/S288C.hgbed.beddb --filetype beddb --datatype gene-annotations --name 'S288C Annotations' --coordSystem S288C --coordSystem2 S288C
$
$ higlass list_tilesets
tileset: Tileset [name: Chromosomes (BY4742)] [ft: chromsizes-tsv] [uuid: RxHwI16wRfWVbI7n1JdrqA]
tileset: Tileset [name: Chromosomes (S288C)] [ft: chromsizes-tsv] [uuid: cc5_AipXQwaJj_ERs_c-iw]
tileset: Tileset [name: A364] [ft: cooler] [uuid: JD9UGPOxQ5uNEo99ETop9g]
tileset: Tileset [name: S288C Annotations] [ft: beddb] [uuid: AYHFQB_1TlS6y2wOW1Iafw]
$
```
![Screenshot 2021-10-13 at 08 35 57](https://user-images.githubusercontent.com/7288036/137088169-8424a7ef-e353-4d90-a7e0-c72d1c3bee46.png)

The screenshot you posted looks like it will be just right. Thanks again
