### ISSUE TITLE
Missing link to docs

### ISSUE THREAD

**Issue by wsnoble** [higlass/higlass#1064]
This one is trivial: when I went to the main page for higlass, I clicked on the word "docs" in this sentence and got a "page not found" error:

Take a look at some examples or head over to the docs to learn how HiGlass can be used and configured. 

(Lemme know if there is some other place I should report something like this.)

**Comment by wsnoble** [comment]
The URL that is not working is https://higlass.io/docs

**Comment by wsnoble** [comment]
It took me quite a bit of clicking around, but I eventually figured out that the correct URL is supposed to be https://docs.higlass.io/

This needs to be fixed in multiple places, including the one mentioned above as well as the "Docs" link at the bottom of the main page.

**Comment by pkerpedjiev** [comment]
Apologies and thanks for the heads-up! We actually had fixed that but never updated the public deployment at higlass.io. 

I just redeployed and it looks like it works now. And this is a perfect place to report things like this. Thank you for taking the time!
