### ISSUE TITLE
wget error from tutorial

### ISSUE THREAD

**Issue by wsnoble** [higlass/higlass#1065]
I was starting to install higlass and tried to follow the instructions here to download a sample dataset

https://docs.higlass.io/tutorial.html#prerequisites

Alas, this yields a 403 error:
'''
 $ wget https://data.4dnucleome.org/files-processed/4DNFI2A4OBS9/@@download/4DNFI2A4OBS9.mcool -O sample.mcool
</files-processed/4DNFI2A4OBS9/@@download/4DNFI2A4OBS9.mcool -O sample.mcool
--2021-11-01 23:09:55--  https://data.4dnucleome.org/files-processed/4DNFI2A4OBS9/@@download/4DNFI2A4OBS9.mcool
Resolving data.4dnucleome.org (data.4dnucleome.org)... 52.22.31.246, 52.73.54.55
Connecting to data.4dnucleome.org (data.4dnucleome.org)|52.22.31.246|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2021-11-01 23:09:56 ERROR 403: Forbidden.
'''

**Comment by pkerpedjiev** [comment]
Oh, lovely. Here's another one you can use:

https://pkerp.s3.amazonaws.com/public/dixon2012-h1hesc-hindiii-allreps-filtered.1000kb.multires.cool

I'll fix the docs right now. Thanks for the heads up!

**Comment by pkerpedjiev** [comment]
Just updated the docs.
