### ISSUE TITLE
Tutorial example hangs indefinitely

### ISSUE THREAD

**Issue by wsnoble** [higlass/higlass#1066]
I am trying to start the tutorial here:

https://docs.higlass.io/tutorial.html#prerequisites

I downloaded the sample.mcool file you sent me in response to my previously posted issue. I also installed docker and started it up.  I then ran the command

```
% higlass-manage view sample.mcool
loads % higlass-manage view sample.mcool
Pulling latest image... 
```

I don't get any error message, but it hangs at the step shown above. Any advice on what I might be doing wrong?

I am running macOS 11.6, Docker Desktop 4.11 (69879), python 3.9.5.

**Comment by pkerpedjiev** [comment]
Hmmm, could you try this:

```
docker pull higlass/higlass-docker
```

**Comment by wsnoble** [comment]
OK, that seems to have helped.  It showed progress downloading, with this final message:

```
Status: Downloaded newer image for higlass/higlass-docker:latest
                                                               docker.io/higlass/higlass-docker:latest
```

However, I then re-ran the original command, and it chugged away for a while and then yielded an error (see attached log file). It seems like I need to install a python module. Is this supposed to have been taken care of automatically by the script?

[log.txt](https://github.com/higlass/higlass/files/7468140/log.txt)

**Comment by nvictus** [comment]
It looks like `higlass-python` is the missing package. I don't think `higlass-manage` was using it until recently, so this does look like a missing install [requirement](https://github.com/higlass/higlass-manage/blob/master/setup.py). I'll raise a separate issue there to fix it.

Try `pip install higlass-python`.

**Comment by wsnoble** [comment]
OK, that got me a bit further. It installed fine, and I ran the command with no error. It yielded this output:

```
 % higlass-manage view /tmp/sample.mcool
loads % higlass-manage view /tmp/sample.mcool
state True
temp_dir: /tmp/higlass-docker
Inferred filetype: cooler
Inferred datatype: matrix
(base) wnoble@Williams-MacBook-Pro Downloads % 
```

However, the window in Firefox shows the HiGlass logo and menu at the top, but the window is all grey (see attached).  I assume I should see data here?

<img width="1680" alt="Screen Shot 2021-11-03 at 2 32 49 PM" src="https://user-images.githubusercontent.com/22529318/140171431-f6756e8f-e52a-4059-9f34-034375c8e36f.png">

**Comment by nvictus** [comment]
In case it just initialized out of view, could you try to zoom to data extent?

![image](https://user-images.githubusercontent.com/1270651/140181738-b5d30517-11b3-45be-9a4f-5d601704541e.png)

**Comment by wsnoble** [comment]
Yes, I just tried that.  It just says "Loading ..." in the upper left
corner.

**Comment by nvictus** [comment]
Could you share:

* A screenshot of the firefox browser console (option+cmd+I or ctrl+shift+I)
* Log files `~/hg-data/log/error.log`, `~/hg-data/log/hgs.log`

**Comment by wsnoble** [comment]
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/22529318/140358794-d6694ab0-235d-43f7-a1b7-7af4646f4829.png">

[error.log](https://github.com/higlass/higlass/files/7476069/error.log)
[hgs.log](https://github.com/higlass/higlass/files/7476071/hgs.log)

**Comment by wsnoble** [comment]
Please don't worry about this for now. I tried it on a different mac and everything works fine. I suspect that the problem on the other mac has to do with the sample mcool file being corrupted. That mac is at home, so I'll double check tonight.

**Comment by nvictus** [comment]
Yes, indeed, the `hgs.log` says that the file couldn't be opened.

**Comment by wsnoble** [comment]
Yes, confirmed that the problem was file corruption on my end.
