### ISSUE TITLE
Clarifying the documentation

### ISSUE THREAD

**Issue by wsnoble** [higlass/higlass#1067]
I have some questions and suggestions regarding this section of the documentation:

<img width="678" alt="image" src="https://user-images.githubusercontent.com/22529318/140438164-f46d3256-c5b7-4f51-867f-c3294b8acd68.png">

Please clarify, in the first sentence, whether multivec is a text-based or binary format.

The second sentence is, I think, missing the word "each" and has misspelled "chromosome."

After the first code block, it says "This can be aggregated ..."  What is "this?"  I think the first code block has created an HDF5 file called `blah.hd5`.  However, the second code block makes no mention of that file, so it's hard for me to understand how the two code blocks are related to each other.

It would also be helpful to include the contents of the `chrom_info.txt` file (I assume it's just `chr1 10000`?).

And I'm left wondering what is the row-infos-filename option and what that file contains.

Finally, I'm not sure of the logical relationship between this section ("Multivec files") and the subsequent sections.  In particular, how does what we learned in this section related to "Other data (multivec)"? That section seems to imply that multivec files are text, not hdf5.

Again, please let me know if this is not the right forum to post these kinds of questions, since they really have nothing to do with the code per se.

**Comment by pkerpedjiev** [comment]
This is definitely the right forum. Thank you for the input! The multivec spec is still a work in progress which may explain (but not excuse) the confusion in that section. Until we spruce it up and at the risk of causing further confusion, here is the spec that we've been (very slowly) working on to define multivec files:

https://paper.dropbox.com/doc/Multivec-Spec--BVlBnY0uhAfONcAGYPV_oiS4Ag-3IelZjzjXDo7mGy3SkGUF

**Comment by pkerpedjiev** [comment]
I just updated the docs to include your suggestions. Thanks a ton for the input!
