### ISSUE TITLE
Cannot run example from jupyter tutorial

### ISSUE THREAD

**Issue by wsnoble** [higlass/higlass#1068]
I am trying to run the first example from this page:

https://docs.higlass.io/jupyter.html

I successfully ran the three installation commands:

```
pip install jupyter higlass-python
jupyter nbextension install --py --sys-prefix --symlink higlass
jupyter nbextension enable --py --sys-prefix higlass
```

I then cut-and-pasted the next code block:

```
from higlass.client import View, Track
import higlass


view1 = View([
    Track(track_type='top-axis', position='top'),
    Track(track_type='heatmap', position='center',
          tileset_uuid='CQMd6V_cRw6iCI_-Unl3PQ',
          server="http://higlass.io/api/v1/",
          height=250,
          options={ 'valueScaleMax': 0.5 }),
])

display, server, viewconf = higlass.display([view1])
display
```

Alas, this did not work.  The errors are below.  What is libfuse?  Do I need to install it separately?

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-1-8970176611fb> in <module>
     12 ])
     13 
---> 14 display, server, viewconf = higlass.display([view1])
     15 display

~/opt/anaconda3/lib/python3.8/site-packages/higlass/viewer.py in display(views, location_syncs, value_scale_syncs, zoom_syncs, host, server_port, dark_mode, log_level, fuse, auth_token)
    158                 tilesets += [track.tileset]
    159 
--> 160     server = Server(
    161         tilesets, host=host, port=server_port, fuse=fuse, log_level=log_level
    162     )

~/opt/anaconda3/lib/python3.8/site-packages/higlass/server.py in __init__(self, tilesets, host, port, name, fuse, tmp_dir, log_level, log_file)
    362         if fuse:
    363             self.fuse_process = FuseProcess(op.join(tmp_dir, "higlass-python"))
--> 364             self.fuse_process.setup()
    365         else:
    366             self.fuse_process = None

~/opt/anaconda3/lib/python3.8/site-packages/higlass/server.py in setup(self)
    233             http and https directories
    234         """
--> 235         from simple_httpfs import HttpFs
    236 
    237         if not op.exists(self.http_directory):

~/opt/anaconda3/lib/python3.8/site-packages/simple_httpfs/__init__.py in <module>
----> 1 from .httpfs import HttpFs
      2 
      3 __version__ = "0.4.12"

~/opt/anaconda3/lib/python3.8/site-packages/simple_httpfs/httpfs.py in <module>
     17 import numpy as np
     18 import requests
---> 19 from fuse import FUSE, FuseOSError, LoggingMixIn, Operations
     20 from tenacity import (
     21     retry,

~/opt/anaconda3/lib/python3.8/site-packages/fuse.py in <module>
    113 
    114 if not _libfuse_path:
--> 115     raise EnvironmentError('Unable to find libfuse')
    116 else:
    117     _libfuse = ctypes.CDLL(_libfuse_path)

OSError: Unable to find libfuse
```

**Comment by wsnoble** [comment]
It seems that, at least on mac, you need to do something like `brew install osxfuse` or `port install osxfuse`. Perhaps the docs should be updated to reflect this as a prerequisite.

**Comment by wsnoble** [comment]
Two things:

First, the `oxsfuse` package in macports seems to be busted.  It's better to use `port install macfuse`.

Second, after I successfully installed it, I still get the same error listed above.  :(

Any advice?

**Comment by alexpreynolds** [comment]
This might be another option to install libfuse on macOS: https://osxfuse.github.io/

**Comment by wsnoble** [comment]
Yes, that helped.  Thanks!

Unfortunately, though it now runs and I can interact with the higlass window, there is no actual data shown.  I can zoom in and out, but everything is grey.  Not sure if this related to the libfuse issue or not:

<img width="1327" alt="image" src="https://user-images.githubusercontent.com/22529318/140594342-e4bb7374-4c4b-43d4-9d0b-a8578abedcc0.png">

I'm not sure how to debug this.  There are no errors in the window where I started the jupyter notebook. And the logs under ~/hg-data don't seem to be updated.

**Comment by pkerpedjiev** [comment]
Can you try clicking on "Zoom to data extent?"

![image](https://user-images.githubusercontent.com/2143629/140596864-31d54f69-8ea5-41cb-b735-b2d4a4aed813.png)

For the fuse issue, you can usually get away with passing in `fuse=False` to the `display` function:

```
display, server, viewconf = higlass.display([view1], fuse=False)
```

**Comment by wsnoble** [comment]
Ah yes, that worked.  I think it would be good to update the docs to mention this step.

**Comment by pkerpedjiev** [comment]
Thanks for the heads up! I just updated the docs.
