### ISSUE TITLE
Avoiding the empty gray box

### ISSUE THREAD

**Issue by wsnoble** [higlass/higlass#1071]
I am a new user of HiGlass, and I am trying to use it to visualize an arbitrary numpy matrix, following the example given in the "Jupyter examples" page. When I first loaded my matrix, I just got an empty viewport, like this:

<img width="1122" alt="image" src="https://user-images.githubusercontent.com/22529318/142143809-0c47c8cc-f74e-4619-a754-c342f2eb1ffd.png">

After experimenting for a bit, I learned that it was possible for me see the matrix if I kept only a small submatrix and rescaled the values to a much smaller range.  Here is what I get:

<img width="1122" alt="image" src="https://user-images.githubusercontent.com/22529318/142143940-18d91cf6-c320-470a-b7b6-d4f4353573b8.png">

I achieved this result by extracting a submatrix of size 2000x2000 and raising the entire matrix to the power 0.1.  I find that if I use all of the 82548 rows of the matrix or if I expand the range of values to the original range (0 to 2166895104), then I am back to the grey screen.  Selecting "zoom to extent" doesn't solve the problem.

Is there something I can do to be able to visualize this entire matrix?

Here's the code:

```
import scipy.sparse as sparse 

compressed_matrix_file="DIA-S4-1.npz"
noisy_sparse = sparse.load_npz(compressed_matrix_file).tocsr()
# load the whole matrix
noisy = noisy_sparse.toarray()
# load part of the matrix
rt_min = 0
rt_max = 2000
mz_min = 38000
mz_max = 40000
noisy = noisy_sparse.toarray()[rt_min:rt_max]
noisy = np.transpose(noisy)[mz_min:mz_max]
print(noisy.shape)
noisy = np.power(noisy, 1/10)
print(noisy.min(), noisy.max())

ts = Tileset(
    tileset_info=lambda: npmatrix.tileset_info(noisy),
    tiles=lambda tids: npmatrix.tiles_wrapper(noisy, tids)
)

display, server, viewconf = higlass.display([
    View([
        Track(track_type='top-axis', position='top'),
        Track(track_type='left-axis', position='left'),
        Track(track_type='heatmap',
              position='center',
              tileset=ts,
              height=250),

    ])
])
display
```
[DIA-S4-1.npz.gz](https://github.com/higlass/higlass/files/7552186/DIA-S4-1.npz.gz)

**Comment by wsnoble** [comment]
FWIW, I can't reproduce this error on my end.  I just got rid of all the higlass stuff and did this, yielding no error:

```
import scipy.sparse as sparse 
import numpy as np

compressed_matrix_file="DIA-S4-1.npz"
noisy_sparse = sparse.load_npz(compressed_matrix_file).tocsr()
# load the whole matrix
noisy = noisy_sparse.toarray()
# load part of the matrix
rt_min = 0
rt_max = 2000
mz_min = 38000
mz_max = 40000
noisy = noisy_sparse.toarray()[rt_min:rt_max]
noisy = np.transpose(noisy)[mz_min:mz_max]
print(noisy.shape)
noisy = np.power(noisy, 1/10)
print(noisy.min(), noisy.max())

a = np.pad(
        noisy,
        ((0, 136), (0, 396)),
        "constant",
        constant_values=(np.nan, np.nan),
    )
```
(2000, 2000)
0.0 8.421058950476793

**Comment by pkerpedjiev** [comment]
Ahh, to get the error, I took out all of the transformations and just did this:

```
compressed_matrix_file="../data/DIA-S4-1.npz"
noisy_sparse = sparse.load_npz(compressed_matrix_file).tocsr()
# load the whole matrix
noisy = noisy_sparse.toarray()

a = np.pad(
        noisy,
        ((0, 136), (0, 396)),
        "constant",
        constant_values=(np.nan, np.nan),
    )
```

My understanding was that it worked after taking a submatrix and taking a power. I wanted to remove that step to see why the original wasn't working.

**Comment by pkerpedjiev** [comment]
Oh, it's because the matrix is of type `int64` and ints don't support nans. If you convert it to float, you can view the matrix without subsampling. Try using the following line when creating `noisy`:

```
noisy = noisy_sparse.toarray().astype(float)
```

You'll get something like this (cropped):

![image](https://user-images.githubusercontent.com/2143629/142504035-6be8de0e-d3f8-4e73-af7c-2d77c4354503.png)

**Comment by wsnoble** [comment]
Excellent, thanks!

Now the only remaining question is why I can only make a picture of a matrix containing ~3000 rows.  In the code below, if I changed 'mz_min = 36000' to use 35000 (or anything smaller), then I am back to the dreaded gray box. Is there a limit on the number of rows/columns that can be displayed?


```
from higlass.client import View, Track
import higlass
import scipy.sparse as sparse 
import numpy as np

compressed_matrix_file="DIA-S4-1.npz"
noisy_sparse = sparse.load_npz(compressed_matrix_file).tocsr()

# load the whole matrix
noisy = noisy_sparse.toarray().astype(float)

# load part of the matrix
mz_min = 36000
mz_max = 40000
noisy = np.transpose(noisy)[mz_min:mz_max]
print(noisy.shape)
print(noisy.min(), noisy.max())

ts = Tileset(
    tileset_info=lambda: npmatrix.tileset_info(noisy),
    tiles=lambda tids: npmatrix.tiles_wrapper(noisy, tids)
)

display, server, viewconf = higlass.display([
    View([
        Track(track_type='top-axis', position='top'),
        Track(track_type='left-axis', position='left'),
        Track(track_type='heatmap',
              position='center',
              tileset=ts,
              height=500),

    ])
])
display
```

**Comment by pkerpedjiev** [comment]
The original matrix has only 2422 rows, no?

```
>>> compressed_matrix_file="../data/DIA-S4-1.npz"
>>> noisy_sparse = sparse.load_npz(compressed_matrix_file).tocsr()
>>> # load the whole matrix
>>> noisy = noisy_sparse.toarray()

>>> noisy.shape
(2422, 82548)
```

**Comment by wsnoble** [comment]
Yes, sorry I wasn't clear.  There is a transpose operation later, so ultimately the one I'm trying to visualize has 82548 rows.  What I'd like to do is replace 'noisy = np.transpose(noisy)[mz_min:mz_max]' with 'noisy = np.transpose(noisy)' but that doesn't work.

**Comment by pkerpedjiev** [comment]
Ahh, I see. Thanks for the clarification. I can reproduce the error. I'll poke around and see what the problem is.

**Comment by pkerpedjiev** [comment]
OK, so that was a bug. Would be able to try out the `pkerpedjiev/npmatrix-narrow` branch to see if it works as expected?

```
git checkout -b pkerpedjiev/npmatrix-narrow https://github.com/higlass/clodius.git
cd clodius
pip uninstall clodius
python setup.py develop
```

This is the output I see with that branch:

![image](https://user-images.githubusercontent.com/2143629/142570668-af5daf6f-bc56-4060-b0b9-323ba2edfad1.png)

**Comment by wsnoble** [comment]
I tried to do this, but I ran into a few snags.

First, I think I have to clone the repo first because I got this message:

```
 git checkout -b pkerpedjiev/npmatrix-narrow https://github.com/higlass/clodius.git
<trix-narrow https://github.com/higlass/clodius.git
fatal: 'https://github.com/higlass/clodius.git' is not a commit and a branch 'pkerpedjiev/npmatrix-narrow' cannot be created from it
```

So instead I did

```
 proj % git clone https://github.com/higlass/clodius.git
Cloning into 'clodius'...
remote: Enumerating objects: 5652, done.        
remote: Counting objects: 100% (291/291), done.        
remote: Compressing objects: 100% (195/195), done.        
remote: Total 5652 (delta 187), reused 155 (delta 87), pack-reused 5361        
Receiving objects: 100% (5652/5652), 27.57 MiB | 7.85 MiB/s, done.
Resolving deltas: 100% (3925/3925), done.
% cd clodius/
cd clodius/
% git checkout -b pkerpedjiev/npmatrix-narrow 
 clodius % git checkout -b pkerpedjiev/npmatrix-narrow 
Switched to a new branch 'pkerpedjiev/npmatrix-narrow'
```

However, I can't pip uninstall clodius because I never installed it.

```
% pip uninstall clodius
pip uninstall clodius
WARNING: Skipping clodius as it is not installed.
```

Instead, I had previously followed the instructions here: https://docs-python.higlass.io/getting_started.html

Nonetheless, I ran the `python setup.py develop` command, but the behavior is still the same. I suspect this is because I did not uninstall clodius.  Do I need to do somethng to get rid of the originally installed version?

**Comment by pkerpedjiev** [comment]
Interesting... you must have clodius installed because it's a dependency of higlass-python. And the tiles function here, `npmatrix.tileset_info` comes from the clodius package.

```
    tileset_info=lambda: npmatrix.tileset_info(noisy),
```

Are you using the same virtual environment for your notebook and the place you tried installing clodius?

I just issued a new release so you can now do `pip install clodius>=0.17.1` to get the latest version.

**Comment by wsnoble** [comment]
Yes, after I installed the new version it works.  Thanks!
