### ISSUE TITLE
Typescript Declaration Files

### ISSUE THREAD

**Issue by riyavsinha** [higlass/higlass#1108]
Has there been any discussion regarding writing Typescript declaration files for the higlass library? Having inline documentation, typing, and IDE suggestions would be immensely helpful when writing applications using this!

**Comment by pkerpedjiev** [comment]
Yup, @manzt did some work on this but for some reason I can't find the PR. Maybe he can point you in the right direction?

**Comment by manzt** [comment]
Currently we maintain an incomplete set of  higlass of types internally [in gosling.js](https://github.com/gosling-lang/gosling.js/blob/master/src/missing-types.d.ts). Ideally we could generate .d.ts files for higlass directly from the JSDoc comments, but I haven’t had the bandwidth to take that effort on.

**Comment by riyavsinha** [comment]
Ok, thank you I appreciate that resource at least. My types stub so far is [here](https://github.com/flekschas/enhancer-gene-vis/blob/v2/src/types/higlass.d.ts), I will just make duplicate the gosling types into the project for now. 

I did make an attempt to use the `emitDeclaration` option only for the typescript compiler in Higlass but that ended up outputting a bunch of types with mostly just `any`s unfortunately
