### ISSUE TITLE
Using a recent version of `npm` gives error when install packages

### ISSUE THREAD

**Issue by sehilyi** [higlass/higlass#1110]
```sh
$ npm --version
8.12.2

$ npm clean-install
```

<img width="1499" alt="Screen Shot 2022-08-23 at 10 49 18" src="https://user-images.githubusercontent.com/9922882/186190339-3466feb2-18a8-4a03-ad85-9e1f15bb9f6f.png">

**Comment by manzt** [comment]
I assume this is for a development install of this repo (e.,g `cd higlass && npm install`)? If so, please pull the latest changes from `develop` and try again? We blew away the old package-lock.json, so I assume this issue is likely fixed.

**Comment by sehilyi** [comment]
Nice, can confirm that it is working!

**Comment by pkerpedjiev** [comment]
Yeah I probably accidentally checked in that packag-lock.json file when doing development on a work machine. All npm packages came from a proxy there. Good that it's fixed.
