### ISSUE TITLE
Where is the Genome position search box?

### ISSUE THREAD

**Issue by MyBiscuit** [higlass/higlass#1133]
I am running a local instance of HiGlass with Docker. I don't see a Genome position search box and cannot select a genome assembly, like here:
[http://higlass.io/app/?config=Z-VHUGPCR1O-KQ3e61dvGQ](url)

> The genome position search box can be enabled from the view menu.

Where is the view menu?
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/85445902/201983174-10376419-84bd-4afc-a3ac-059499ddc56e.png">

**Comment by sehilyi** [comment]
Hi! You can click on the 'gear' button on the top right and then click on the "Toggle position search box".

![Screenshot 2022-11-15 at 13 12 00](https://user-images.githubusercontent.com/9922882/201994716-167c0ef0-617a-4ec2-a81b-9e8b6e9c7102.png)
