### ISSUE TITLE
Getting some datasets / higlass slack channel

### ISSUE THREAD

**Issue by manuelfmerino** [higlass/higlass#1190]
Hello,

I'm trying to further analyze some cooler files. They are in the higlass server, but not all of them are in 4DN and the processing looks slightly different. I would really need to get those in the server, and I saw in previous issues here that maybe asking for them through Slack could be an option. Is that still a thing?

Thanks,
Manuel

**Comment by etowahadams** [comment]
Hi @manuelfmerino,

The link to the Slack can be found [here](https://higlass.io/about#contact). Feel free to ask a question there! As I understand it you're trying to analyze some cooler files, but don't have them in your higlass server yet? I would recommend checking out the following links if you have not already. 

1. [Tutorial](https://docs.higlass.io/tutorial.html)
3. [Cooler data preparation](https://docs.higlass.io/data_preparation.html#cooler-files)

**Comment by manuelfmerino** [comment]
Sorry, I wasn't very clear! I meant that the experiments are some of the default ones that can be visualized in the higlass server but I needed the actual .mcool files. I asked for them in the Slack channel and just got them! Thanks a lot.
