### ISSUE TITLE
Higlass public datasets unavailable

### ISSUE THREAD

**Issue by MarcoDiS** [higlass/higlass#1201]
From the beginning of the week the public datasets that higlass was automatically loading in my private session are no longer available. That's not the main problem because I can still use the data I uploaded.

It is also missing the "Toggle position search box" option that is very handy when navigating contact maps. 

Could you help me to solve this problem?

**Comment by pkerpedjiev** [comment]
Hiccup with the higlass server. Should be fixed now.

**Comment by MarcoDiS** [comment]
Thanks! It works now!
