### ISSUE TITLE
same-origin cookies not preserved in tile-proxy.js#json() in Chrome

### ISSUE THREAD

**Issue by scottx611x** [higlass/higlass#287]
_Commit_: https://github.com/hms-dbmi/higlass/commit/9b6592abab5b2662a4599af2d838592d97470888

#### Steps to reproduce
1.  Load a track in a recent version of Chrome

#### Observed behavior
* Note how the `d3-request` [above this TODO](https://github.com/hms-dbmi/higlass/blob/30bc4779f4a7892293a092965a7b7025e2f21a22/app/scripts/services/tile-proxy.js#L556) does not preserve `same-origin` cookies.

#### Expected behavior
- For cookies to be preserved

Take note that recent versions of d3 utilize the `Fetch API` which ["doesn't send any cookies by default"](https://stackoverflow.com/a/50726741)

**Comment by mccalluc** [comment]
I believe we fixed this: The TODO is gone, and it looks like the code is jumping through the right hoops to keep credentials: 
```
return fetch(url, { credentials: 'same-origin', headers })
```

We can reopen or file a new issue if there are still problems.
