### ISSUE TITLE
add a line or something between chromosomes for bedgraph (bw) tracks on higlass

### ISSUE THREAD

**Issue by SooLee** [higlass/higlass#300]
_Commit_: 

#### Steps to reproduce
1.

#### Observed behavior
- 

#### Expected behavior
-

**Comment by flekschas** [comment]
@SooLee Could you give a little (visual) example what you're looking for? Maybe it's already supported.

**Comment by mccalluc** [comment]
Chatted with Soo yesterday: She just wanted to point out that for most end users, the chromosome grid and labels should be on by default.

To follow up with that, I talked with Chad after the standup this morning, and we agreed that it isn't something that we should try to hard-code into HiGlass, but that the client code he's writing should handle that. So, I'll close this issue, and on slack I'll ask Chad to confirm that my understanding is correct, and if it's useful, add a cross-reference from this to his work.
