### ISSUE TITLE
Multivec does not properly rerender

### ISSUE THREAD

**Issue by flekschas** [higlass/higlass#326]
http://higlass.io/app/?config=L4nKi6eGSzWOpi-rU2DAMA

#### Steps to reproduce
1. resize track
2. resize browser

#### Observed behavior

![oct-01-2018 16-27-07](https://user-images.githubusercontent.com/932103/46314241-01c21e80-c598-11e8-8ca2-be10d83d7242.gif)

![oct-01-2018 16-36-56](https://user-images.githubusercontent.com/932103/46314354-4a79d780-c598-11e8-92a8-4e356aeb396d.gif)

#### Expected behavior
- should properly rerender

**Comment by pkerpedjiev** [comment]
Fixed in v0.2.0-alpha.5
