### ISSUE TITLE
SVG API export problems

### ISSUE THREAD

**Issue by alexpreynolds** [higlass/higlass#327]
_Commit_: 

* Master branch of higlass
* Compiled version of Danielle's higlass-multivec
* Compiled version of master branch of higlass-website
* Master branch of higlass-server

#### Steps to reproduce
1. Initialize higlass container
2. Use `zoomTo()` API call to relocate view to genomic position
3. Use `exportAsSvg()` API call to export SVG

I have experimented with using `setTimeout()` to delay the execution of `exportAsSvg()` until after `zoomTo()` is given time to complete rendering (between 0-5 seconds), but the SVG output has the same render issues.

#### Observed behavior

1. Chromosome track includes position labels from initial viewconf genomic position, as well as the position labels from to the post-`zoomTo()` call
2. Track label components are not positioned correctly (specifically, the data resolution labels are left-aligned in the web view, but are centered in the SVG view)

Example SVG file is available here: https://gist.github.com/alexpreynolds/743af70631575bf1ecbad425e5034d13

In this example, the browser is initialized to a position on chrX and a `zoomTo()` call moves the browser to a position on chr3. The chromosome track contains labels from both chromosomes. 

The SVG output should look similar to this:

<img width="1061" alt="test" src="https://user-images.githubusercontent.com/33584/46536327-03733700-c863-11e8-9852-ca8395eead7a.png">

However, this is the observed output (converted to PNG):

<img width="940" alt="test2" src="https://user-images.githubusercontent.com/33584/46536506-99a75d00-c863-11e8-84d9-6dd7047d2389.png">

#### Expected behavior
- Track content should match the post-`zoomTo()` genomic position shown in the source web container
- Track label components should match alignment and position of components in web container

**Comment by alexpreynolds** [comment]
An `exportAsPng()` API call appears to render chromosome tracks and labels more correctly, e.g., here is what comes out of this call for the above test:

![localseleniumtest2](https://user-images.githubusercontent.com/33584/46559793-44406f80-c8a6-11e8-8d48-0c7820308f26.png)

The viewport projection is not rendered, but the rest of the views in the PNG render appear to be consistent with the web browser view.

**Comment by alexpreynolds** [comment]
Hi Peter,

I spoke too soon, I'm afraid. It looks like the SVG rendering problems show
up in the v0.2.0-alpha.3 patch you emailed about earlier today. Also, if I
select the "Export as SVG" menu option to manually export an SVG file, the
tracks back in the web view are subsequently redrawn with the segmented
vertical offset problem, where the left and right thirds of a track are
staggered up or down in stair-step fashion.

**Comment by pkerpedjiev** [comment]
Crap. Do you have a link I could reproduce this with?

**Comment by alexpreynolds** [comment]
Yes, please see:

http://explorer.altius.org/app/?config=SUFTOi4wT5S79NgyLKPTcg&chr=chr3&start=181600000&stop=181800000

I have a hook that looks for positional query parameters and then calls
zoomTo() on the higlass-translated coordinates.

Using the "Export as SVG" option shows the issue (as well as an automated
exportAsSvg() call via a headless Selenium session).

**Comment by pkerpedjiev** [comment]
Could this be a caching issue? I just tried it with this example and don't see the segmented vertical offset issue (although the bars are missing borders).

Here's a screenshot of the output SVG:

![image](https://user-images.githubusercontent.com/2143629/46706420-5998ff00-cc02-11e8-87af-d971148267fa.png)

Does that look more or less correct or is there something there that's wrong?

**Comment by alexpreynolds** [comment]
The initial view is correct. However, once `zoomTo()` is used, the SVG is corrupted.

**Comment by alexpreynolds** [comment]
The PNG output tends to look correct (though the viewport projection is missing). This seems to be a problem with how the view is transformed to SVG after a coordinate change, specifically.

**Comment by pkerpedjiev** [comment]
Wait a second!

> the SVG is corrupted, with the effects described above (misplaced and overlapping chromosome and track labels)

Isn't this a different issue? https://github.com/hms-dbmi/higlass/issues/327

That will be fixed in the next HiGlass release. 

> the
tracks back in the web view are subsequently redrawn with the segmented
vertical offset problem, where the left and right thirds of a track are
staggered up or down in stair-step fashion.

This is the issue I've been looking for here. Is this still a problem? And if so, do you have an example of it happening?

**Comment by alexpreynolds** [comment]
It's kind of difficult to describe in words but an animation would show this more clearly. I'll post a video clip later tonight.

**Comment by alexpreynolds** [comment]
Here is a video of the behavior of the 0.2.0alpha3 multivec plugin, without exporting to SVG:

https://www.youtube.com/watch?v=fhsThpVWIoQ

In this video, the vertical offset problem does not appear. Scrolling to the left or right shows the tracks being rendered with a constant vertical offset. This is the "expected" behavior.

Here is a video of the behavior of this higlass server instance running the same updated multivec plugin. We load the same viewconf, export the views to SVG, and scroll the top-most panel to the left or right:

https://www.youtube.com/watch?v=Wb8HPiIH7wo

In this second video, the tracks look normal at first. But after exporting the views to SVG and scrolling to the left or right, it looks like the multivec tracks do not have a correct or consistent vertical offset. 

The "stair-step" effect shows up after scrolling in hidden portions of the track up- or downstream of the viewconf's original genomic range.

Interestingly, a vertical shift upwards seems to happen as soon as the mouse pointer enters the top-most epilogos multivec track.

**Comment by pkerpedjiev** [comment]
You're right. A video helps a lot. I got it reproduced and will try to fix it ASAP.

**Comment by alexpreynolds** [comment]
Thanks, as usual!

**Comment by pkerpedjiev** [comment]
Could you try v0.2.0-alpha.5?

**Comment by pkerpedjiev** [comment]
Thanks for your patience and help in getting this resolved. Could you try `v0.2.0-alpha.7`? I think this issue should be fixed there, along with another mouseover bug.

**Comment by alexpreynolds** [comment]
This seems to work much better, thanks!

**Comment by pkerpedjiev** [comment]
One of the more satisfying issues to close :)
