### ISSUE TITLE
1d-heatmap-track-2.html not working

### ISSUE THREAD

**Issue by mccalluc** [higlass/higlass#349]
_Commit_: 89a91e0eca1

#### Steps to reproduce
http://localhost:8080/1d-heatmap-track-2.html
```
react-dom.development.js:1542 Uncaught TypeError: _assign is not a function
    at react-dom.development.js:1542
    at validateFormat (react-dom.development.js:15)
    at react-dom.development.js:16
hglib.js:129 Uncaught TypeError: Cannot read property 'render' of undefined
    at launch (hglib.js:129)
    at Object.viewer (hglib.js:182)
    at 1d-heatmap-track-2.html:157
```

#### Expected behavior
- No error, but beyond that, not sure.
- Does this do something different than 1d-heatmap-track.html?

**Comment by mccalluc** [comment]
@flekschas : This is another example it looks like you checked in, but here it's more than just missing data. Remove the example, or fix, as you think best? Thanks!

**Comment by flekschas** [comment]
Issue with 3rd party libs.
