### ISSUE TITLE
Production build is broken

### ISSUE THREAD

**Issue by flekschas** [higlass/higlass#360]
_Commit_: Since v1.2.4

#### Steps to reproduce
1. Use `https://unpkg.com/higlass@1.2.8/dist/hglib.min.js`

#### Observed behavior
- `window.hglib not defined`

**Comment by mccalluc** [comment]
I get this console error: 
```
Uncaught TypeError: Cannot read property 'rgb2hex' of undefined
```
I'll try to see what commit caused the problem and propose a fix.

**Comment by flekschas** [comment]
Ah but good pointer! I forgot to link the two!

**Comment by mccalluc** [comment]
@flekschas : I believe this is fixed? Or if you'd prefer to keep this open till the next release, reopen?
