### ISSUE TITLE
afterAll removeHGComponent doesn't need done()?

### ISSUE THREAD

**Issue by mccalluc** [higlass/higlass#374]
After some of the other PRs are cleared up, see if you can replace
```
    afterAll((done) => {
      removeHGComponent(div);
      done();
    }
```
with 
```
    afterAll(() => {
      removeHGComponent(div);
    }
```

The done parameter is only useful if it's being passed in as a callback, I think?

**Comment by pkerpedjiev** [comment]
> The done parameter is only useful if it's being passed in as a callback, I think?

Yup. A lot of times I just used it out of habit. But it doesn't have to be there.

**Comment by mccalluc** [comment]
Cool: Thank you for your patience with these minor questions!
