### ISSUE TITLE
tooltip values on the website do not match numbers on the colorbar

### ISSUE THREAD

**Issue by mimakaev** [higlass/higlass#395]
on higlass.io if you enable tooltip, it shows values of 1e-11 and 1e-10 in trans. The colorbar however goes only from 1e-4 to 1. Is this behavior expected?

**Comment by mimakaev** [comment]
I believe it actually shows e^-9 as 1e-9, which is incorrect. This notation assumes log10, not ln 
https://en.wikipedia.org/wiki/Scientific_notation#E-notation

**Comment by flekschas** [comment]
@pkerpedjiev is this the code that defines the tooltip value? https://github.com/higlass/higlass/blob/b24df1b5cfbb376c8d74526d7faf601f7ce57193/app/scripts/HorizontalLine1DPixiTrack.js#L59

**Comment by pkerpedjiev** [comment]
No, it's here: https://github.com/higlass/higlass/blob/c285469d6bb503d76c81e85e8ca8dfa4eb39d2cb/app/scripts/HeatmapTiledPixiTrack.js#L1269

Max is right, it's displaying the natural logarithm as the base 10 logarithm. We actually do it the correct way a few lines up: https://github.com/higlass/higlass/blob/c285469d6bb503d76c81e85e8ca8dfa4eb39d2cb/app/scripts/HeatmapTiledPixiTrack.js#L1241

I'll submit a PR right now and we can fix it in 1.3.0.
