### ISSUE TITLE
Setup automated git hook for lint testing

### ISSUE THREAD

**Issue by flekschas** [higlass/higlass#403]
_Commit_: develop

Now that @mccalluc has set up enforced ESLint check we should add git hooks so that we don't accidentally commit corrupted files which pollute the git history.

For HGA I am using [ESLint](https://github.com/eslint/eslint) + [Prettier](https://github.com/prettier/prettier) + [Husky](https://github.com/typicode/husky) + [LintStaged](https://github.com/okonet/lint-staged)

- ESLint defines strict rules
- Prettier autoformats you code nicely
- Husky setups git hooks
- LintStaged takes care of automatic linting and code style fixing

The setup works pretty well.

Check https://github.com/higlass/higlass-app/blob/master/.lintstagedrc and https://github.com/higlass/higlass-app/blob/master/package.json#L120 for the setup.

Therefore, 🚫💩 as LintStaged advocates!

**Comment by mccalluc** [comment]
Husky has been in place for a while, and it works.

@flekschas : Of the four parts you listed above, I think we're missing Prettier. Reopen, or file a new issue, if you think it's important?

 Closing.
