### ISSUE TITLE
Zoom in/out does page scroll at the same time on firefox

### ISSUE THREAD

**Issue by KorayKirli** [higlass/higlass#479]
_Commit_: 

#### Steps to reproduce
1. Visit higlass.io with Firefox browser (64.0) and try zooming in on one of the HiGlass views.

#### Observed behavior
- While the view zooms in the page continues to scroll

#### Expected behavior
- Scroll should be disabled while cursor is in HiGlass view.

**Comment by flekschas** [comment]
This might be a hiccup while HiGlass loads. Do you experience the issue at any time or only at the beginning when the page loads?

**Comment by mccalluc** [comment]
@KorayKirli : I have seen this in the past, but I'm not seeing it now. FF 66.0.5. Closing, but please reopen or file a new issue if there is still a problem.
