### ISSUE TITLE
current higlass website "jiggles" 

### ISSUE THREAD

**Issue by mimakaev** [higlass/higlass#488]
_Commit_: 

#### Steps to reproduce
1. Create Hi-Glass with two views or more 
2. Share it as link, and then open a link in a web browser, preferably Chrome. 
3. With some probability, it will start to "jiggle" as in this video. 
https://www.youtube.com/watch?v=MaTmlYLcyhQ

4. It does seem to happen in chrome on Ubuntu on a 4K screen. It doesn't happen in Firefox. 
It happens in Chromium shipped with 18.04, but not right away (see below). 
5. If it doesn't happen right away, clicking on the menus and buttons randomly, and/or moving mouse around, will trigger it. 
6. Resizing the screen back-and-forth seems to temporarily cure it. But not always. I had some links with complex layouts that were nearly permanently "ruined" and would not stop jiggling. 

This link has a minimal setup that jiggles for me: 
http://higlass.io/app/?config=ZACNp9-1RKC-5PwguuS2Qw

#### Observed behavior
- 

#### Expected behavior
-

**Comment by mccalluc** [comment]
@mimakaev : Have you been able to reproduce this on a Mac, or is it possible it's only on Ubuntu? And could you see what version number of Chrome you have? I've been unable to reproduce with Version 71.0.3578.98.

**Comment by mimakaev** [comment]
Hi,

I don't have a Mac, but I have a windows laptop. I tried reproducing it on
windows, and it doesn't jiggle. I however remember seeing it on my windows
laptop at some point. I also tried reproducing it on some other computers,
and it didn't jiggle
.
I have Chrome 72.0.3626.28. But it also jiggles in Chromium that ships with
Ubuntu 18.04. It may be something specific to my machine/drivers.

Max

**Comment by pkerpedjiev** [comment]
This may be related to the window size of the window. HiGlass uses react-grid-layout which forces the window into 12 grid units of width. If the grid adjusts its size, it might be triggering the cascade of actions that happen when the window is resized forming a loop.

Here's where that happens: https://github.com/higlass/higlass/blob/33ab2644d55add5dced0abcb949ccb7229935aa5/app/scripts/HiGlassComponent.js#L670

I've seen this behavior sporadically but had a hard time reproducing it. A workaround may be to just resize the window slightly.

**Comment by mimakaev** [comment]
Stopped being reproducible for me. Potentially because of software upgrade on my machine. Hence, closing.
