### ISSUE TITLE
gene - annotation tracks

### ISSUE THREAD

**Issue by trotskys** [higlass/higlass#500]
Hey All

Guys, we need your help.

We would like to load gene annotation tracks to our local higlass docker environment.
To remove default files we ammended configuration and removed higlass.io from trackSourceServers, as result we lost gene annotation tracks as well.

I see that there is a documentaion describing this process.

curl -u `cat ~/.higlass-server-login`    \
    -F "datafile=@/Users/peter/data/tiled-data/gene-annotations-${ASSEMBLY}.db"    \
    -F "name=Gene Annotations (${ASSEMBLY})"   \
    -F 'filetype=beddb'  \
    -F 'datatype=gene-annotation'  \
    -F 'coordSystem=${ASSEMBLY}' \
    -F 'coordSystem2=${ASSEMBLY}'  \
    http://higlass.io:80/api/v1/tilesets/

Could I ask you to share with me already prepared db files such as:
gene-annotations-hg19.db
gene-annotations-hg38.db
gene-annotations-mm10.db
gene-annotations-mm9.db

**Comment by pkerpedjiev** [comment]
Hey, were you able to get these files from the 4DN portal?
