### ISSUE TITLE
How to see my own cooler files?

### ISSUE THREAD

**Issue by LeonardoLed** [higlass/higlass#511]
Hi there, I have a problem, I've followed this note:
_https://github.com/higlass/higlass-manage_
with this command:

**_docker exec higlass-container python higlass-server/manage.py ingest_tileset --filename /tmp/dixon_2M.cool --datatype matrix --filetype cooler_**

 in order to see my cooler files in higlass, but it seems that it doens't work 

Even I checked the admin site and it shows this:
![image](https://user-images.githubusercontent.com/33387734/50809679-c471d900-12ca-11e9-9e82-cc452fd9f5c0.png)

I only want to add new track in my view.

![image](https://user-images.githubusercontent.com/33387734/50809642-8379c480-12ca-11e9-8b3c-ab35fffdd8ca.png)

I would be very grateful to you If you could help me.
Thanks a lot.

**Comment by pkerpedjiev** [comment]
It looks like it should be working. Could you run

```
curl localhost:8888/api/v1/tilesets/
```

And post the output here?

Also, can you try:

```
higlass-manage stop
higlass-manage start --no-public-data
```
And post the same screenshot of the higlass client from above?

**Comment by pkerpedjiev** [comment]
One more thing to try:

```
higlass-manage start --version v0.4.33
higlass-manage ingest dixon_2M.cool
```

**Comment by LeonardoLed** [comment]
That's perfect it works for me, Thank you.

**Comment by flekschas** [comment]
Closing this as the problem seems to be resolved
