### ISSUE TITLE
Adding chromosome and coordinate labels 

### ISSUE THREAD

**Issue by dphansti** [higlass/higlass#537]
Question not an issue.

I can't figure out how to get chromosome and coordinate labels to appear.

HiC data was processed in Juicer using their default version of chromosome name (i.e. 1,2,3 not chr1, chr2, chr3).  HiC files were converted to .cool files and ingested into higlass.

I have ingested the chromsize file too (with chrom names = 1,2,3,etc).

```higlass-manage ingest --filetype chromsizes-tsv --datatype chromsizes --assembly hg19 /Path/to/hg19.chrom.sizes```

How do I get the coordinates to appear?

Thanks

**Comment by pkerpedjiev** [comment]
You can add a track on top of type `horizontal-chromsizes-labels`:

![image](https://user-images.githubusercontent.com/2143629/51767268-db764080-20aa-11e9-9687-29bcc528473c.png)

Or you can overlay a grid of type `2d-chromosome-grid`:

![image](https://user-images.githubusercontent.com/2143629/51767316-f5178800-20aa-11e9-997b-13117bcbdca5.png)

You should be able to reach those options by searching for the name of the dataset you added (hg19.chrom.sizes)

**Comment by dphansti** [comment]
Perfect.  Thanks!
