### ISSUE TITLE
Add an option to manually set data resolution

### ISSUE THREAD

**Issue by yguoma** [higlass/higlass#541]
I would like to suggest adding an option to manually set the data resolution (bin size). I want to be able to generate a large image for a relatively small region using a larger bin size than the automatic one. That is, I want to have less number of pixels in the image, with large pixel size.

**Comment by flekschas** [comment]
Have you tried setting a zoom limit?

![screen shot 2019-01-28 at 8 13 22 pm](https://user-images.githubusercontent.com/932103/51877167-345b0880-2339-11e9-8dcf-44236cb4ee67.png)

Otherwise, could you go a little bit into the details on how you want to generate the data or visually set the bin size?

**Comment by flekschas** [comment]
Yes! You just need to open the track context menu and go to "zoom limits". It can be deactivated in the same way. See the screenshot below, which probably explains it in an easy way:

![screen shot 2019-01-29 at 9 38 33 am](https://user-images.githubusercontent.com/932103/51915691-b8e56f80-23a9-11e9-99b0-029607d91492.png)

**Comment by yguoma** [comment]
Thank you. That solves my problem.

Yuchun
