### ISSUE TITLE
Document pre-commit hooks in README?

### ISSUE THREAD

**Issue by mccalluc** [higlass/higlass#542]
Follow up to  #475: Should there be instructions for new developers in the README on how to get the pre-commit hooks set up?

**Comment by flekschas** [comment]
Nope. All you have to do is `npm i`.

**Comment by mccalluc** [comment]
Nifty: Just tried it out. (If anyone does want to commit fast to their own work-in-progress branch, `--no-verify` is available.)

Thanks!
