### ISSUE TITLE
Overlay tracks are drawn outside the track extent

### ISSUE THREAD

**Issue by flekschas** [higlass/higlass#545]
_Commit_: v1.3.1

#### Steps to reproduce
1. Add overlay tracks

#### Observed behavior
- See how the horizontal 1D annotation is drawn over the gene annotation track although the vertical track does not exist?

![screen shot 2019-01-28 at 7 48 20 pm](https://user-images.githubusercontent.com/932103/51877298-b21f1400-2339-11e9-8823-4651c0729c55.png)

#### Expected behavior
- Overlays should only be drawn within the track extent / dimension

**Comment by pkerpedjiev** [comment]
Fixed in v1.4.0
