### ISSUE TITLE
Support view scrolling for large stacks of 1D tracks

### ISSUE THREAD

**Issue by flekschas** [higlass/higlass#571]
Currently, HiGlass creates a canvas element that's as high as the sum of all tracks. While this works fine in most uses cases where the height is smaller than the browser height or not that much higher. But in cases where many tracks are stacked on top of each other, the graphics card will start complaining or the performance will go down as a lot of pixels are rendered that are actually off screen.

Therefore, it would be great to have a scrolling mode (in extension to `options.bounded`) in which HiGlass creates a canvas element that is as high as the parent element in the DOM and implements a scroll behavior as shown here: https://codepen.io/wiledal/pen/ZYoNEa?editors=0010 or https://gist.github.com/slashman/79f4441a27367b661bdb86702493e44b

One thing to keep in mind is that scrolling over a track will normally lead to a zoom behavior of that track so the user either needs to disable zooming or we could utilize the ALT key to restore the normal scrolling. Similar as the ALT key can be used to get the normal context menu instead of the HiGlass context menu.

**Comment by pkerpedjiev** [comment]
Not sure if I see a scroll behavior in the codepen 🤔

**Comment by flekschas** [comment]
It's for touch input. But you should be able to see it here: https://github.com/higlass/higlass/pull/572 😉

**Comment by alexpreynolds** [comment]
Might this work for non-touch devices, where the display is vertically
smaller than the view/viewconf?

**Comment by flekschas** [comment]
Yes, that's the idea. Right now what's happening is that either the canvas object gets grows (in the unbounded case), which can lead to problems, or that the available space for each track decreases (in the bounded case).

But really the idea is just to be able to scroll in a fixed-size canvas element.
