### ISSUE TITLE
toggle position search box not working

### ISSUE THREAD

**Issue by eaststar0** [higlass/higlass#586]
_Commit_: 

Hello, I've been using higlass for over a year now.
I use docker to launch higlass and always update it to the latest version.
Today, toggle position search box stopped working. Also, cannot find any reference genome from the drop down menu.
It seems like same thing happens for the higlass.io website.
I'm wondering if it's something related to my computer or from the software.
I also re-installed the docker but it still behaves the same.
![image](https://user-images.githubusercontent.com/1015952/54252640-d826ff00-4508-11e9-9ad2-b2d32f5f6fee.png)
![image](https://user-images.githubusercontent.com/1015952/54252651-e2e19400-4508-11e9-8b3c-02ef15e9f467.png)

Thank you

Dongsung

**Comment by flekschas** [comment]
Thanks for reporting! This is certainly a bug

Do you remember which version you used before when it was still working?

@pkerpedjiev Any idea what the issue might be?

**Comment by flekschas** [comment]
Okay, I found out why. It's an issue with `higlass-server`. The following API returns a 500 error:

http://higlass.io/api/v1/available-chrom-sizes/

@pkerpedjiev Can you look into that? I haven't worked with the server lately.

**Comment by pkerpedjiev** [comment]
Fixed on higlass.io and in higlass-docker:v0.6.9.
