### ISSUE TITLE
Zoom limit is not controllable if hi-c matrix is loaded on top panel?

### ISSUE THREAD

**Issue by eaststar0** [higlass/higlass#588]
Hello,

Thank you very much for your fast response in my previous report.

I'm currently loading my Hi-C matrices on top panel to load multiple samples.
I just noticed that the zoom limit is not adjustable if they are loaded on the panels other than the center.
Can you please check on this?

Also, since I was working with multiple samples, I was thinking it would be great if we can adjust height of track by type in number or adjust multiple tracks at once by choosing tracks to be adjusted so we can have tracks in the same sizes.

Thank you very much!!

Dongsung

**Comment by flekschas** [comment]
> I'm currently loading my Hi-C matrices on top panel to load multiple samples.
I just noticed that the zoom limit is not adjustable if they are loaded on the panels other than the center.

Is this a bug report or feature request? I.e., did it used to work before?

> I was thinking it would be great if we can adjust height of track by type in number or adjust multiple tracks at once by choosing tracks to be adjusted so we can have tracks in the same sizes.

I am afraid that's not possible through our UI currently but you can easily achieve this by editing the view config's `height` property of your tracks.

Also, would you mind using the [template](https://github.com/higlass/higlass/issues/new) in the future? We added it to track basic information, e.g., which version of HiGlass are you using (open the web dev console and you will see a log with message with the version number), how can we replicate the issue, and what is the expected outcome. Thanks! 🙂

**Comment by eaststar0** [comment]
The version I'm using is 1.4.0
I tested with 0.6.1 and is still not working.

I apologize for not using the template. I'll use the template in the future for sure.

Thank you very much!!

Dongsung

**Comment by flekschas** [comment]
Thanks for the update. I am still not sure if you are suggesting a new feature or reporting a bug.

Were you able to adjust the zoom limit before version v1.4.0? If so, have you tried version v1.5.0? (on htp://higlass.io for example?)

**Comment by eaststar0** [comment]
I just figured zoom limit doesn't work with my mcool files but the ones uploaded from you are working fine.
I actually changed the resolutions when I make the mcool file. 
I'll test what happens if I make the mcool file again with default resolutions and let you know the result.
My mcool files work fine in the center. 

Thank you for your time

![image](https://user-images.githubusercontent.com/1015952/54407349-b5c4eb00-469a-11e9-890c-ec2990801d89.png)

**Comment by pkerpedjiev** [comment]
It's a bug, it's really easy to fix and I'll have a fix by the end of the weekend.

For setting identical heights, the easiest option is to export the the viewconfs as jsons, set the height properties of your tracks and then drag the saved json onto either higlass.io/app or localhost:8989/app or wherever you're hosting your higlass instance. 

Sorry for the inconvenience. There's a growing number of suggestions we're gathering about how to set track options and your feedback is really valuable.

**Comment by pkerpedjiev** [comment]
Fix is here: https://github.com/higlass/higlass/pull/589

Should be in the next release. Still shooting for the end of the weekend :)

**Comment by eaststar0** [comment]
This is really helpful. 
Thank you very much!!!

**Comment by pkerpedjiev** [comment]
New release is out:

HiGlass version: 1.5.1
Docker version: 0.6.11

Please reopen the issue if you encounter any problems.
