### ISSUE TITLE
newest chrome scroll context

### ISSUE THREAD

**Issue by burakalver** [higlass/higlass#596]
_Commit_: 

#### Steps to reproduce
1. Update to newest chrome (73.0.3683.86)
2. Go to higlass.io.
3. "scroll down" with mouse on the topmost higlass display, with the intention that it should zoom out.

#### Observed behavior
- the page is scrolled down. with a glitchy mix of zoom-out.

#### Expected behavior
- the page should stay put and the display should zoom out.

**Comment by flekschas** [comment]
Seems to be related to

```
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See <URL>
```

https://www.chromestatus.com/features/6662647093133312

**Comment by pkerpedjiev** [comment]
Easy fix: https://github.com/higlass/higlass/pull/597
