### ISSUE TITLE
Lower gene annotations remove prematurely

### ISSUE THREAD

**Issue by flekschas** [higlass/higlass#601]
_Commit_: latest

#### Steps to reproduce
1. http://higlass.io/app/?config=LSIavCZPQQ-nL80iUg_4qg
2. Drag the view to the left and see how the gene annotation disappears (or checkout the gif below)

![Mar-30-2019 20-49-24](https://user-images.githubusercontent.com/932103/55283298-f9bc1f00-532d-11e9-9277-9eea05fd9c3f.gif)

#### Observed behavior
-The gene annotation disappears

#### Expected behavior
- The gene annotation should remain visible

The is caused by the fact that annotation is stretched over many tiles and that the "source" tile that holds the annotation data is being removed as it's too far outside the correct view field.

E.g.:

```
// View:
                   |---------|
// Tiles:
[source][------][------][------][------]
// Gene annotation:
    <-[]-----[]------[]
```

but because the `[source]` tile is too far outside it gets removed and sadely the beautiful gene annotation is gone forever 😭 (until you zoom out again or pan to towards the gene start site 😇)

**Comment by pkerpedjiev** [comment]
Those annotations were built with an older version of clodius. Just replaced them with annotations from a newer version and they seem to work fine. Re-open if you notice this issue again.
