### ISSUE TITLE
When exporting a viewconf trackSourceServers is set incorrectly

### ISSUE THREAD

**Issue by flekschas** [higlass/higlass#615]
_Commit_: v1.5.3.

#### Steps to reproduce
1. Export a viewconfig from a server with custom gene-annotations or chrom coords

#### Observed behavior
- The `trackSourceServers` is set to `/api/v1`, which will lead to a 404 error when requesting the gene annotations or chrom sizes
- Changing `trackSourceServers` to the server from which the viewconfig was exported fixes the issue

#### Expected behavior
- `trackSourceServers` should be set to the exporting server or there should be a warning somewhere that viewconfigs can't be used on another machine without manual changes.

#### Example
Export a view from the server mentioned in https://github.com/higlass/higlass/issues/612#issuecomment-482348660 and try viewing it locally. The matrix loads fine but the coords are broken.

**Comment by alexander-veit** [comment]
This issue seems to be fixed in version 1.8.3.
