### ISSUE TITLE
 "export view as svg or png" with adjusted 2d-rectangle-domains doesn't generate picture as indicated

### ISSUE THREAD

**Issue by eaststar0** [higlass/higlass#637]
_Commit_: v1.5.3

#### Steps to reproduce
1. Do "export view as svg or png" with bedpe loaded matrix with adjusted color and opacity

#### Observed behavior
- Doesn't generate picture with colors on "2d-rectangle-domains"
If I export:
![image](https://user-images.githubusercontent.com/1015952/56935980-84b54400-6aa9-11e9-818b-dd567dd2942c.png)
It gives me:
![image](https://user-images.githubusercontent.com/1015952/56935993-9565ba00-6aa9-11e9-9079-510750a1b5a1.png)

#### Expected behavior
- export view as what I have on Higlass

**Comment by pkerpedjiev** [comment]
Hey, thanks for reporting. Should be fixed in docker v0.6.14 and on higlass.io. Please reopen if that's not the case.
