### ISSUE TITLE
Add a copy-to-clipboard button to the export viewconf URL dialog

### ISSUE THREAD

**Issue by nvictus** [higlass/higlass#648]
Because highlighting text and ctrl+c is just so laborious... ;)

Also, the viewconf URLs can be longer than the dialog box and it's easy to miss a few characters at the end by not dragging the cursor far enough... I've also found it easy to accidentally click somewhere outside the modal, which closes it before I manage to copy (that's probably a bug).

**Comment by flekschas** [comment]
At least the text should be highlighted by default so that you only need to hit `CTRL+C`

**Comment by flekschas** [comment]
Actually, having to click on a button or hitting `CTRL+C` is already waaay too much work. As a lazy person, I want to be spoon fed and have the link already be copied to the clipboard for me.
