### ISSUE TITLE
PNG export is broken

### ISSUE THREAD

**Issue by pkerpedjiev** [higlass/higlass#688]
_Commit_: 

#### Steps to reproduce

1. Go to the view config menu and click "Export views as PNG"

#### Observed behavior

- Nothing happens.

#### Expected behavior

- A PNG representation of the current view is exported.

**Comment by alexpreynolds** [comment]
Could it be related to this issue: https://github.com/higlass/higlass/issues/652

Fritz had a patch for this which resolved the problem, but I think it changed how PNG data were made.

**Comment by flekschas** [comment]
This might actually be related to the broken SVG export reported in #651

Having fixed #651 in #713 the PNG export works as usual. Also, the promise gets resolved.

**Comment by flekschas** [comment]
This seems to be fixed. PNGs are properly exported for me. Please reopen if you still encounter the issue.

**Comment by einanf** [comment]
Hi, I am running HiGlass locally using docker and "Export views as PNG" does not work for me.
I'm managing the instance using docker because higlass-manage cannot be compiled on my windows computer in case it matters.

**Comment by pkerpedjiev** [comment]
Hey, sorry about that! Would you pasting the output of `http://localhost:8989/version.txt` here? (You may have to change the port in that URL)

Also, what browser are you using?

I just tried it locally and it seems to work but I'm on OS X running Chrome.

**Comment by fpaldi** [comment]
Hi,

I'm experiencing the same issue with our HiGlass server (but not when I'm running HiGlass locally). None of the exports work.

Any ideas? I'm using Chrome and the following versions: 

SERVER_VERSION: 1.9.0
WEB_APP_VERSION: 1.0.5
LIBRARY_VERSION: 1.4.1
HIPILER_VERSION: 1.3.1
MULTIVEC_VERSION: 0.2.0
CLODIUS_VERSION: 0.10.0
TIME_INTERVAL_TRACK_VERSION: 0.2.0-rc.2
