### ISSUE TITLE
Horizontal heatmap is fuzzy at high resolution (but only for some datasets?)

### ISSUE THREAD

**Issue by liz-is** [higlass/higlass#707]
_Commit_: 

#### Steps to reproduce
1. Some Hi-C datasets are "fuzzy" when zoomed in at high resolution, but only when displayed as  "horizontal-heatmap" - the same file as a 2D heatmap is fine. Publicly available datasets, and, oddly, .mcool files I produced earlier, are fine. I can't provide you with this specific file to test, but might be able to provide a different example.

#### Observed behavior
- Some tracks are fuzzy, see the bottom left in the screenshot.
![Screenshot 2019-06-25 at 16 54 09](https://user-images.githubusercontent.com/3035709/60109377-89753c00-976a-11e9-88dd-c1ffd0d2921a.png)

#### Expected behavior
- Individual bins/pixels visible when zoomed in, like in the top left (my other dataset), and right hand side (public datasets).

I thought this was a higlass issue but now I'm suspecting it's with the file itself...

**Comment by flekschas** [comment]
This is very odd. An example config where this happens would be super helpful. It looks like a rendering issue but HiGlass should never use anything other than NearestNeighbor interpolation when scaling up the matrix.

Could you also provide some more background information like the version of HiGlass (open the web console to see it) and the browser & OS versions.

**Comment by liz-is** [comment]
Strangely, this is no longer happening! I went to test it again in a different browser and can't reproduce it in either that or the original browser. I have no idea why - I did update HiGlass today (to 0.7.2), but I'm sure I tested with the new version... I'm going to close this for now, unless I see it again. Sorry for the trouble.

**Comment by pkerpedjiev** [comment]
I stealthily fixed that a few weeks ago 😁 If you encounter it again, please re-open this issue. It's pretty straightforward to fix by setting PIXI.js interpolation settings.
