### ISSUE TITLE
Different color scales applied without re-rending the whole thing consistently

### ISSUE THREAD

**Issue by mccalluc** [higlass/higlass#73]
_Commit_: 
SERVER_VERSION: 0.2.6
WEBSITE_VERSION: 0.5.6

#### Steps to reproduce
1. Start with a small-ish browser window.
1. Load http://higlass.io/app/?config=PwGNs8hlTjK9M3rUbcXs1Q and slowly pan left

#### Observed behavior
- around chr8:50MG, the tile is rendered in a distinctly darker pallette.

#### Expected behavior
- The whole screen at any moment in time should be using the same pallette.

(Underlying issue same as #52?)

**Comment by pkerpedjiev** [comment]
This should be fixed by the call to `updateExistingGraphics` in `TiledPixiTrack`.
