### ISSUE TITLE
Ctrl-z on viewconf editor kills viewer

### ISSUE THREAD

**Issue by pkerpedjiev** [higlass/higlass#732]
_Commit_: 

#### Steps to reproduce

1. Open viewconf editor
2. Make some change
3. Hit CMD-Z (undo)

#### Observed behavior

Entire higlass page disappears

#### Expected behavior

The undo command works as expected 

![Jul-10-2019 09-33-08](https://user-images.githubusercontent.com/2143629/60987307-2e108580-a2f6-11e9-842c-8a51358e0304.gif)

**Comment by flekschas** [comment]
Did you do this through `higlass-app`?

**Comment by flekschas** [comment]
```Cannot read property 'views' of null```

Seems a HG issue

**Comment by flekschas** [comment]
There is some weridness going on locally but it doesn't crash

**Comment by flekschas** [comment]
FYI, on higlass.io `CMD+Z` it works for me but on higlass.io/app it doesn't

**Comment by flekschas** [comment]
It's related to higlass-app, which incorrectly intercepted CMD+Z even when an input element was focused. Will fix the issue there
