### ISSUE TITLE
How do I upgrade to a newer version?

### ISSUE THREAD

**Issue by dphansti** [higlass/higlass#749]
I am running HiGlass locally.  I installed with pip.  How can I upgrade to a newer version of HiGlass?  Also, how can I see what version I am running?

**Comment by pkerpedjiev** [comment]
Hey, sorry for the delayed reply. If you're running locally, you can go to `http://localhost:8989/version.txt` to see the versions of all the components.

If you're using `higlass-manage`, you can see the version using `higlass-manage version`. To upgrade to the latest version, all you need to do is `higlass-manage start`. That will pull the latest Docker container and start it.

**Comment by pkerpedjiev** [comment]
By the way, for future reference, feel free to pop into our Slack channel (http://bit.ly/higlass-slack) and either ask there or paste a link to the GitHub issue. That will ensure a speedier response.

**Comment by flekschas** [comment]
Closing this. Reopen if it's still an issue.
