### ISSUE TITLE
How to stop automatic rescaling

### ISSUE THREAD

**Issue by dphansti** [higlass/higlass#751]
Often when I move the map a little bit the value scaling changes.  I haven't zoomed in or out.  I haven't changed resolution.  And I haven't touched the value scaling (legend thing on top right).   Is it possible to avoid?

**Comment by dphansti** [comment]
Response I received

"it’s because the color scaling is determined by the minimum and maximum values of the visible tiles. When you scroll to the left or right, new tiles are loaded and the bounds change.

Is there a way to avoid that? I actually think there is but you have to use the new viewconf editor."

**Comment by dphansti** [comment]
"Take a look here: https://docs.higlass.io/view_config.html#track-options
you should be able to edit the viewconf and add valueScaleMin and valueScaleMax values to the heatmap options. Something like this:
{
   'type': 'heatmap',
   'server': 'my.server.org/api/v1/tilesets',
   ...
   'options': {
      'valueScaleMin': 0.0001,
     'valueScaleMax': 10,
   }
}"

**Comment by pkerpedjiev** [comment]
Thanks for transcribing! For anybody that may stumble across this, the issue was resolved on our Slack channel: http://bit.ly/higlass-slack
