### ISSUE TITLE
gaps form when viewing multivec files

### ISSUE THREAD

**Issue by burakalver** [higlass/higlass#784]
_Commit_: 

#### Steps to reproduce
1. zoom in and out of a multivec file. In particular, using a test multivec where each chromosome just has one state and the whole genome is covered.

http://54.88.112.8:8170/app/?config=N_6g3tnfRUOy_9QzQaDwDw
(note that we might not maintain this server or link indefinitely.)

#### Observed behavior
- some times gaps open up.

#### Expected behavior
- there should be no gaps.

![examples](https://user-images.githubusercontent.com/16612140/65981281-c4ac9880-e446-11e9-972c-9445142536e6.png)

**Comment by alexander-veit** [comment]
It seems this was an issue with an older version of higlass-server (at least it was not related to clodius or the viewer). I have deployed a new version to the server above and can't see gaps anymore. Please check.
