### ISSUE TITLE
troubles with parameter --chromsizes-filename in clodius

### ISSUE THREAD

**Issue by Kononkov** [higlass/higlass#786]
_Commit_: 
Hi
#### Steps to reproduce
1. Creating an aggregated file with 'clodius aggregate bedpe' with parameter --chromsizes-filename, when clodius is running from the docker. I am working with reduced genome dm3, use chromosomes chr2L,chr2R,chr3L,chr3R and chrX. Attempts to use parameter --chromsizes-filename aren't successful, clodius asks for assembly. I use correct order of chromosomes in file (as they are listed above).
 Command:
docker run -v /tmp/clodius/:/tmp/   gehlenborglab/clodius   clodius aggregate bedpe  --chromsizes-filename /tmp/input/dm3.chrom.sizes  --chr1-col 1 --from1-col 2 --to1-col 3 --chr2-col 4 --from2-col 5 --to2-col 6 /tmp/input/tads.txt 

#### Observed behavior
- KeyError: "ERROR converting chromosome position to genome position. Please make sure you've specified the correct assembly using the --assembly option. Current assembly: hg19, chromosomes: chr2L,chr2L"

#### Expected behavior
- to get aggregated file with my reduced genome

**Comment by pkerpedjiev** [comment]
Hi Alexander, the Docker container must be out of date. Would you mind installing `clodius` using pip and trying again?

Here is the relevant line in the source showing that you should be seeing a different error message: https://github.com/higlass/clodius/blob/1672e8e91d905cc9d5647a3ec3fafe5f4d2b2ca4/clodius/cli/aggregate.py#L212

**Comment by Kononkov** [comment]
Thanks a lot for quick answer!
 Now I'm on the right way.
