### ISSUE TITLE
Error in converting .hic to .cool

### ISSUE THREAD

**Issue by rahmas36** [higlass/higlass#788]
Hi, I want to try out this new protocol called Cut-C, which combines Micro-C with Cut and Run to identify protein-centric interactions at high resolution. The authors uploaded .hic files on GEO which I wanted to convert to m.cool to visualize on HiGlass. However, when converting the .hic file to .cool I received this error message: ... This does not appear to be a HiC file; magic string is incorrect.
I cannot load this file on Juicebox. What could be the problem? I attached the link to the file in question. 

https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM3587377

I downloaded the ftp link.

**Comment by pkerpedjiev** [comment]
Hey, may I suggest asking on the `hic2cool` GitHub repository? https://github.com/4dn-dcic/hic2cool/issues

**Comment by rahmas36** [comment]
Ok thanks! I submitted my question to the hic2cool repository.

**Comment by pkerpedjiev** [comment]
Link for future reference :-) https://github.com/4dn-dcic/hic2cool/issues/39

**Comment by nvictus** [comment]
Looks like that issue was closed. Did you manage to load the pairs file, @rahmas36?

**Comment by nvictus** [comment]
Feel free to re-open if you still encounter issues.
