### ISSUE TITLE
The bars height change sizes when zooming in and out in multivec files

### ISSUE THREAD

**Issue by Lmercadom** [higlass/higlass#792]
Hi,
When visualizing multivec files in higlass, the height of the bars get smaller as I zoom it and get bigger as I zoom out. Sometimes taking up to 2 times the initial height. 

This is a link to a visualization: 
http://54.88.112.8:8170/app/?config=Y6iIpgA5RaO94e-LM_qV4w

This is the bed file I used to create it:
[SPIN_states_test.bed.gz](https://github.com/higlass/higlass/files/3784668/SPIN_states_test.bed.gz)
[SPIN_states_test_row_infos.txt](https://github.com/higlass/higlass/files/3784669/SPIN_states_test_row_infos.txt)

**Comment by flekschas** [comment]
Sorry for not responding. And thanks for reporting this!

Adding @pkerpedjiev to the conversation if he has ever seen this before.
