### ISSUE TITLE
Two different matrices in split view

### ISSUE THREAD

**Issue by rahmas36** [higlass/higlass#803]
How do I view two different matrices on both sides of the diagonal? Is it possible to do that with the diagonal split matrix, similar to Juicebox? I loaded two of my cool files into HiGlass, and one was set to the upper right. I can't seem to set the other one to the lower left. It just appears blank. What do I do?

**Comment by flekschas** [comment]
Thanks for reporting. This seems to be a bug. Are you working with higlass.io or a local server? If you're using a local server could you tell us which versions you're using. You can quickly find out by going to http://my-local-server.1337/versions.txt (e.g., http://higlass.io/version.txt are the version from higlass.io)

**Comment by flekschas** [comment]
Actually they work just fine but I found out that you have to manually disable the background.

Here's an example of Rao 2014 GM12878 vs K562: http://higlass.io/l/?d=Iw9jNIbTTRS_98e4lr7J3A

**Comment by rahmas36** [comment]
Thanks! It's working now!

**Comment by nvictus** [comment]
There seems to be different behavior re: the disabling background, depending on whether the second heatmap is added via the center panel's cog menu or the view's + menu: 

* Using the cog menu (Add Series) and then setting `Extent` the background is active, blocking the heatmap behind.
* Using the + menu and setting `Extent` the background is set to transparent, as expected.
