### ISSUE TITLE
Heatmap labelPosition bug

### ISSUE THREAD

**Issue by nvictus** [higlass/higlass#812]
1. Set `labelPosition` to `hidden` on a full heatmap -->  Label background disappears, but label text remains. But refreshing or exporting the viewconf makes it work.

2. Set `labelPosition` to anything on [split](http://higlass.io/l/?d=KOBGVvjmQ5qqmmSdTqgwZA) heatmaps --> no effect, even after refresh.

**Comment by alexpreynolds** [comment]
I have found this bug, also, in v1.7.2. 

It seems to affect the first track in a series of tracks in a viewconf's top view. Subsequent tracks do not show the hidden label (as expected).

If I replace the `labelPosition` property (set to `hidden`) with `topLeft` and use a `labelTextOpacity` value of `0`, I can hide the label in that way.

Here are a pair of viewconfs which I have used to test the issue locally:

https://gist.github.com/alexpreynolds/47106b9a0e0b33db41b86678615792b3

This gist contains two viewconfs: `hidden.json` and `topLeft.json`. 

If I drag-and-drop `hidden.json` into the higlass.io site, I can see the label in the first track (as well as in my local site). If I drag in `topLeft.json`, the label is not shown.
