### ISSUE TITLE
Track config menu placed incorrectly

### ISSUE THREAD

**Issue by pkerpedjiev** [higlass/higlass#833]
_Commit_: 

#### Steps to reproduce

1. Go to higlass.io
2. Click on the heatmap track config menu
3. Without closing it, click on the gene annotations config menu

#### Observed behavior

- Gene annotations menu appears where the heatmap menu does

#### Expected behavior

- Gene annotations menu appears by the gene annotations track

![Jan-15-2020 12-07-47](https://user-images.githubusercontent.com/2143629/72467085-14f9fd00-378f-11ea-8c2a-17350f100408.gif)

**Comment by sehilyi** [comment]
It looks this bug is fixed by #911.

**Comment by sehilyi** [comment]
Fixed by #911

**Comment by sehilyi** [comment]
Fixed by #911
