### ISSUE TITLE
Changing the TrackType of a track in a value scale lock group removes the lock

### ISSUE THREAD

**Issue by alexander-veit** [higlass/higlass#847]
#### Steps to reproduce
1. Create two 1d tracks (e.g. bar tracks) and valueScale lock them
2. Change the track type of one of the tracks to e.g. horizontal-line

#### Observed behavior
- The value scales are not syncing anymore. Console shows error. 

#### Expected behavior
- Value scales should stay in sync.

The problem seems to be that the track id changes but this change is not reflected in the valueScaleLocks object (check view conf), which is now pointing to a non-existing track (hence the errors).

**Comment by pkerpedjiev** [comment]
Pre-configured viewconf to try on: http://higlass.io/l/?d=Kq6dwaH9S9af8IWUJc5PDA
