### ISSUE TITLE
Make Configure Series a form menu

### ISSUE THREAD

**Issue by nvictus** [higlass/higlass#854]
https://www.fuckdropdowns.com/

**Comment by nvictus** [comment]
In case I'm using the wrong UIminology, all I mean something that allows configuration of more than one attribute at a time without disappearing. Going through a hierarchical dropdown 10 separate times to configure a single track is a lot of work.

**Comment by nvictus** [comment]
And yeah, the video is actually pretty lame...

**Comment by flekschas** [comment]
Possible duplicate of https://github.com/higlass/higlass/issues/233?

**Comment by nvictus** [comment]
Definite duplicate of #233 :)
