### ISSUE TITLE
Visualize GWAS loci in HiGlass

### ISSUE THREAD

**Issue by rahmas36** [higlass/higlass#866]
Hi, 

Is there a way to load GWAS loci in a BED format into HiGlass? Our lab has an interest in understanding the chromatin interactome of risk loci associated with psychiatric and neurodegenerative disorders. I would like to load this data alongside HiC maps I have generated from different cell types from human brain. Thanks!

**Comment by pkerpedjiev** [comment]
Does this help? http://docs.higlass.io/data_preparation.html#bed-files

**Comment by rahmas36** [comment]
Thank you!

I was able to load the GWAS loci as a BED file

**Comment by sehilyi** [comment]
I am closing this issue since the question had been addressed, but feel free to open this if a related discussion is needed.
