### ISSUE TITLE
Search bar: exact matches not a top of typeahead list

### ISSUE THREAD

**Issue by ngehlenborg** [higlass/higlass#87]
_Commit_: 

#### Steps to reproduce
1. Search for PAM on http://higlass.io

#### Observed behavior
- PAM is not at the top of the list

![image](https://cloud.githubusercontent.com/assets/1216518/23799742/9b0b0080-0577-11e7-9f7b-00d78855344b.png)

#### Expected behavior
- PAM is at the top of the list because it is a perfect match

**Comment by mccalluc** [comment]
This is a server problem, and is covered by https://github.com/higlass/higlass-server/issues/45
