### ISSUE TITLE
Zooming in past units of bases

### ISSUE THREAD

**Issue by alexpreynolds** [higlass/higlass#873]
_Commit_: 

- Current public build of higlass.io
- v1.8.5 higlass + v0.2.2 higlass-multivec (test development server)

#### Steps to reproduce

To reproduce, I pan and zoom into viewport until sub-base units are visible.

#### Observed behavior

We have found that multivec tracks on a test server (v1.8.5 higlass + v0.2.2 higlass-multivec) flicker and disappear when the user is zoomed in at fractional-base resolution, as well as the data in the Rao et al. Hi-C dataset.

Behavior on higlass.io:

![Screen Recording 2020-03-06 at 3 44 42 PM](https://user-images.githubusercontent.com/33584/76131280-bb5dc400-5fc2-11ea-92d6-af5158d2a0e9.gif)

On test server:

![Screen Recording 2020-03-06 at 4 02 27 PM](https://user-images.githubusercontent.com/33584/76131630-1643eb00-5fc4-11ea-8973-c6df2ad6f17b.gif)

#### Expected behavior

Wouter and I chatted about this and, at the lowest level, genomic datasets are typically represented in units of bases. We couldn't think of datasets that would be expressed in smaller units. 

In the general case, it would be useful to lock zooming in past the point of a single base (or perhaps a specified resolution, for data that are coarser). This would also resolve the visual artifacts.

**Comment by pkerpedjiev** [comment]
At its root, this is a float rounding error when the graphics are scaled by a huge amount.

>In the general case, it would be useful to lock zooming in past the point of a single base (or perhaps a specified resolution, for data that are coarser)

Agreed. I think that's a very sensible solution.
