### ISSUE TITLE
Zero-height horizontal tracks appear to be rendered at constant non-zero height

### ISSUE THREAD

**Issue by alexpreynolds** [higlass/higlass#887]
_Commit_: 

higlass v1.9.0

#### Steps to reproduce
1. Set the `height` property of a `horizontal-point` or `horizontal-multivec` track type item to `0`.
2. Set the `minHeight` property of the track's `options` to `0`.

#### Observed behavior
Track is 20 pixels high (possibly `MIN_HORIZONTAL_HEIGHT`).

#### Expected behavior
Track has zero height (i.e., is not shown, and is ideally not rendered or has its tiles queried).

As a workaround, I have found setting the track height to a small, fractional value (e.g. `0.001`) helps to hide the track. (Short-circuiting tile retrieval and rendering are other issues I've been looking into, separately.) Here is a sample viewconf: [test.json.zip](https://github.com/higlass/higlass/files/4429526/test.json.zip)

The reason a zero-height track is useful is to render similar datasets as different track types, by having multiple tracks and setting their heights to zero or non-zero values, depending on the visible genomic scale in the higlass view. 

Some data types, like annotations, are useful at small genomic scales, for example, while a kind of "summary view" that the multivec format allows can be more appropriate at larger genomic scales.

When there are a lot of tracks and only a couple of them change, we've found that creating a new viewconf with a new set of tracks takes longer (several seconds), than simply updating track heights (fraction of a second).

**Comment by pkerpedjiev** [comment]
Whoa, the bug here seems like it's the fact that loading a new viewconf takes several seconds 😮

**Comment by pkerpedjiev** [comment]
But yeah, I think the problem is here:

https://github.com/higlass/higlass/blob/5aa9cc29a8990999cb67f7415539bac04bf7f424/app/scripts/utils/fill-in-min-widths.js#L39

`options.minHeight` evaluates to false if it's equal to 0. It should be like this:

```
          track.height = options.minHeight != undefined || MIN_HORIZONTAL_HEIGHT;
```
