### ISSUE TITLE
Track labels turn into UIDs in context menu after saving changes in viewconf editor

### ISSUE THREAD

**Issue by nvictus** [higlass/higlass#889]
#### Steps to reproduce
1. Load some tracks
2. Open viewconf editor
3. Click save

#### Observed behavior
![image](https://user-images.githubusercontent.com/1270651/78940252-8b9f5180-7a83-11ea-8551-9772173b9a19.png)

#### Expected behavior
- where did the names go?

**Comment by pkerpedjiev** [comment]
Should be fixed in this PR: https://github.com/higlass/higlass/issues/889

**Comment by alexander-veit** [comment]
Fixed in 1.9.2.
