### ISSUE TITLE
Multicooler matrix view does not reflect chromosome ordering

### ISSUE THREAD

**Issue by dmalzl** [higlass/higlass#894]
_Commit_: Recent

Hi,

I am trying to visualize a multicooler with HiGlass including addition of the search position. For this we first generated contact matrices with HiCExplorer (https://hicexplorer.readthedocs.io/en/latest/index.html) at different resolutions and converted them to a multicooler. Although, we anticipated the semantic ordering of the chromosomes and the view displaying the chromosome grid in the right way, the matrix itself is displayed as if the chromosomes are ordered as chr10 chr11 chr12, ..., chr1, chr2, ..., chrX, chrY. 

#### Steps to reproduce
1.  Aligning paired end reads with HICUP pipeline (using bowtie2 index generated from not semantically ordered fasta of mm9)
2. generating 1kb matrix with HiCExplorers hicBuildMatrix
```bash
hicBuildMatrix -s first.bam second.bam -o hicmatrix_1kb.h5 --skipDuplicationCheck --binSize 1000 --QCfolder hicQC -ga mm9 --minDistance $MIN --maxLibraryInsertSize $MAX --threads 16
```
3. reordering chromosomes to reflect semantic order
```bash
hicAdjustMatrix -m hicmatrix_1kb.h5 --chromosomes chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chrX chrY --action keep -o hicmatrix_1kb_canonical.h5
```
4. generating different resolutions (resolutions chosen according to the documentation of HiGlass)
```bash
for i in 5 10 25 50 100 500 1000;
do
    hicMergeMatrixBins -m hicmatrix_1kb_canonical.h5 -o hicmatrix_${i}kb.h5 -nb ${i}
    hicCorrectMatrix correct -m hicmatrix_${i}kb.h5 --correctionMethod KR -o hicmatrix_${i}kb_KR.h5
done
```

5. Convert to multicooler
```bash
h5toCool.py -m *KR.h5 -o hicmatrix.mcool --merge
```
where `h5toCool.py` is a lightweight version of `hicConvertFormat` fixing a bug that would make the resulting multicooler file unreadable by HiGlass due to binary header entries (see also https://github.com/deeptools/HiCMatrix/issues/29)

6. loading file to HiGlass server hosted by our institution with `curl`
```bash
curl -u user:password \
    -F "datafile=@chromosomes_mm9.tsv" \
    -F "filetype=chromsizes-tsv" \
    -F "datatype=chromsizes" \
    -F "uid=chromosomes_mm9" \
    -F "coordSystem=mm9" \
    -F "name=Chromosomes (mm9)" \
    <url2server>

curl -u user:password \
    -F "datafile=@hicmatrix.mcool" \
    -F "filetype=cooler" \
    -F "datatype=matrix" \
    -F "uid=CH12_shLacZ"  \
    -F "coordSystem=mm9" \
    <url2server>
 ```

#### Observed behavior
Anticipating the semantic ordering of the chromosomes by reordering the generated matrix in the file and the HiGlass view displaying the chromosome grid in the right way but the matrix itself is displayed as if the chromosomes are ordered as chr10 chr11 chr12, ..., chr1, chr2, ..., chrX, chrY although examination of the multicooler indicates that the order is correct. (see file attached)

```python
import cooler
c = cooler.Cooler('hicmatrix.mcool::resolutions/1000000')
c.matrix(balance = False, as_pixels = True, join = True)[:10, :10]

   chrom1   start1      end1 chrom2   start2      end2         count
0    chr1  3000000   4000000   chr1  3000000   4000000  16494.401695
1    chr1  3000000   4000000   chr1  4000000   5000000   5958.713133
2    chr1  3000000   4000000   chr1  5000000   6000000   1839.512867
3    chr1  3000000   4000000   chr1  6000000   7000000    638.394715
4    chr1  3000000   4000000   chr1  7000000   8000000    773.033207
5    chr1  3000000   4000000   chr1  8000000   9000000    940.248242
6    chr1  3000000   4000000   chr1  9000000  10000000    474.213159
7    chr1  4000000   5000000   chr1  4000000   5000000  12823.700529
8    chr1  4000000   5000000   chr1  5000000   6000000   5314.330105
9    chr1  4000000   5000000   chr1  6000000   7000000   1552.412464
10   chr1  4000000   5000000   chr1  7000000   8000000   1036.752391
11   chr1  4000000   5000000   chr1  8000000   9000000    817.722504
12   chr1  4000000   5000000   chr1  9000000  10000000    761.359299
13   chr1  5000000   6000000   chr1  5000000   6000000  14334.216266
14   chr1  5000000   6000000   chr1  6000000   7000000   3877.311889
15   chr1  5000000   6000000   chr1  7000000   8000000   1529.875814
16   chr1  5000000   6000000   chr1  8000000   9000000   1144.271438
17   chr1  5000000   6000000   chr1  9000000  10000000    828.638743
18   chr1  6000000   7000000   chr1  6000000   7000000  15439.594502
19   chr1  6000000   7000000   chr1  7000000   8000000   4808.961148
20   chr1  6000000   7000000   chr1  8000000   9000000    980.361631
21   chr1  6000000   7000000   chr1  9000000  10000000   1414.547768
22   chr1  7000000   8000000   chr1  7000000   8000000  12438.445233
23   chr1  7000000   8000000   chr1  8000000   9000000   5837.967332
24   chr1  7000000   8000000   chr1  9000000  10000000   2996.634297
25   chr1  8000000   9000000   chr1  8000000   9000000  14551.815508
26   chr1  8000000   9000000   chr1  9000000  10000000   3897.124364
27   chr1  9000000  10000000   chr1  9000000  10000000  13381.554611
```

#### Expected behavior
We figured that the ordering of the matrix as chr10 chr11 chr12, ..., chr1, chr2, ..., chrX, chrY is due to the ordering in the index used to align the paired end reads. Therefore, we manually reordered the matrices produced by HiCExplorer and expected this to fix the problem (plotting the matrix with different methods also indicated that reordering worked fine)

Do you have a clue why this could be?

The view was generated by first adding hicmatrix.mcool as heatmap in the center and then overlaying it with the 2d-chromosome-grid information of the same file.

![image](https://user-images.githubusercontent.com/52696584/79739816-ff9ced80-82fe-11ea-9b5e-8db59376dbd9.png)

**Comment by pkerpedjiev** [comment]
> We figured that the ordering of the matrix as chr10 chr11 chr12, ..., chr1, chr2, ..., chrX, chrY is due to the ordering in the index used to align the paired end reads.

This is almost certainly not the issue.

If I had to guess, I'd say that the `h5toCool.py` script doesn't load the chromosomes in the proper order, but I could be wrong. Is that script public?

@nvictus any other ideas?

An alternative approach would be to convert your BAM files to pairs and then load them directly to `cooler` using [cooler cload pairs](https://cooler.readthedocs.io/en/latest/cli.html#cooler-cload-pairs).

**Comment by dmalzl** [comment]
Thanks for the quick reply. The `h5toCool.py` script is basically a copy of `hicConvertFormat`  where I simply copied all things necessary from `HiCExplorer` and the `HiCMatrix` library to make it a standalone script and corrected a bug which would make the resulting cooler file unreadable by HiGlass (I attached it). However, I had another look at the code and also tested it and the loading is fine. Furthermore, I reran the pipeline and found that my testsample works fine so it seems there is something going on in the pipeline rather than with HiGlass. Anyway thanks for looking into this complex mess.

[h5toCool.txt](https://github.com/higlass/higlass/files/4508344/h5toCool.txt)

**Comment by dmalzl** [comment]
Update: The problem seems to be related to the deletion of previous files and reupload with the same UUID which seems to keep the data of the first upload, because we first uploaded the matrices with the wrong sorting, then deleted it and then reuploaded the new correct ones. Uploading the new ones with a different uuid and also into a new local instance of the server displays the matrix correctly. Therefore, I will close this issue. Thanks for looking into it

**Comment by dmalzl** [comment]
Hi its me again,

After fiddling with the analysis of the data a bit I was convinced to do everything with cooler and this works really nice. However, the chromosome ordering is again chr10-chr19, chr1-chr9, chrX, chrY. I now use cooler csort and cload to generate the matrices. Do you have a clue what I am doing wrong here (I know this seems to be more of a cooler related problem anyway this thread has all the background of my issue).

Thanks in advance,
Daniel

**Comment by dmalzl** [comment]
Nevermind I think I found the rotting egg here. The csort command relies on the chromosome order the chromSize file has. Thanks for letting me put this here.

**Comment by nvictus** [comment]
Hmm.. `cooler cload` will respect the order of the chromosomes you provide in the chromsizes or bin file input. 

Also, `cooler csort` isn't strictly necessary anymore. [cooler cload pairs](https://cooler.readthedocs.io/en/latest/cli.html#cooler-cload-pairs) accepts unsorted input.

**Comment by dmalzl** [comment]
Thanks, does this then also reflect the right chromosome ordering?

**Comment by nvictus** [comment]
Yes, it uses the ordering in the `BINS` argument (bed file or chromsizes file).

**Comment by dmalzl** [comment]
So this then also reflects the ordering of the chromsize file implicitly? Sorry for the late spam ;)

**Comment by nvictus** [comment]
I'm not entirely sure what you mean, but I think the answer is yes.

e.g. the command

```
cooler cload pairs  -c1 2 -p1 3 -c2 4 -p2 5  {chrom_sizes}:1000 {mypairs} {output_cool}
```

will make sure that the data is loaded such that the internal chromosome order is identical to what is given in the `{chrom_sizes}` file. HiGlass respects this order.

You can check what the chromosome order in a cooler file is with `cooler dump -t chroms`.

**Comment by dmalzl** [comment]
Yes thats exactly what I wanted to know. Thanks, that totally explains why it looks so weird on top of the caching issue of the uuid. Thank you very much again.
