### ISSUE TITLE
HiGlass completely broken in Safari

### ISSUE THREAD

**Issue by ngehlenborg** [higlass/higlass#905]
_Commit_: Current deployment on http://higlass.io 

#### Steps to reproduce
1. Go to http://higlass.io using Safari 13.1 using Mac OS 10.15.4 (Catalina).

#### Observed behavior
<img width="1752" alt="image" src="https://user-images.githubusercontent.com/1216518/80614539-91e27700-8a0c-11ea-9f5c-f25057e9d469.png">

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/1216518/80625365-1936e700-8a1b-11ea-989d-18b0e47e7b7a.png">

The issue appears immediately after loading:
![Apr-29-2020 13-04-29](https://user-images.githubusercontent.com/1216518/80624937-69617980-8a1a-11ea-94a8-7a263d46d742.gif)

#### Expected behavior
Views not overlapping with each other.

**Comment by keller-mark** [comment]
It appears that this behavior occurs when the WebGL 2.0 Safari Experimental Feature is turned on. (Develop -> Experimental Features -> WebGL 2.0)

**Comment by ngehlenborg** [comment]
Great catch @keller-mark! I can confirm that this is indeed an issue caused by the Web GL 2.0 experimental features in Safari. Once I turn those off, it works as advertised.

I will updated the title to make that clear and will close this issue for now.

**Comment by pkerpedjiev** [comment]
@keller-mark How the heck did you figure that out?

**Comment by keller-mark** [comment]
Coincidentally we were also having issues with WebGL 2.0 + Safari with vitessce, which @ilan-gold figured out, and then this issue came to mind as well!
