### ISSUE TITLE
The higlass stylesheet overrides <td> styles in an entire app

### ISSUE THREAD

**Issue by pkerpedjiev** [higlass/higlass#918]
_Commit_: 

#### Steps to reproduce

1. Include higlass as a package in a web application
2. Create a table. Set `border: 0` on the table.

#### Observed behavior

- The table has border because the higlass stylesheet includes `td { outline: 1px solid blask }` as a style

#### Expected behavior

- The table has no borders because higlass's styles are scoped.

**Comment by keller-mark** [comment]
Fixed in https://github.com/higlass/higlass/pull/928
