### ISSUE TITLE
crosshair colour

### ISSUE THREAD

**Issue by atracey99** [higlass/higlass#919]
_Commit_: 

#### Steps to reproduce
1.

#### Observed behavior
- 
The crosshair colour is black.  It would be great if this colour could be changed so I can view the crosshair in combination with my favourite HiGlass colour scheme

#### Expected behavior
-

**Comment by flekschas** [comment]
You can change it via `mousePositionColor` in the view config. E.g., https://flekschas.github.io/higlass-fancy/
