### ISSUE TITLE
vertical divergent bar track type?

### ISSUE THREAD

**Issue by mimakaev** [higlass/higlass#929]
It appears to be missing. 

Would be a helpful feature to have! When working with compartments a lot, it would be nice to have divergent bar charts for X and Y axis, not just on top.

**Comment by pkerpedjiev** [comment]
Thanks for the heads up. This will be part of a larger PR that gets rid of the notion of "horizontal-" and "vertical-" tracks. Should be coming soon.

In the meantime, vertical divergent tracks are actually supported if you just call a vertical-bar track a "horizontal-divergent-bar". See the video below to see how to convert it:

![Jun-14-2020 13-50-03](https://user-images.githubusercontent.com/2143629/84603791-06029e00-ae46-11ea-875e-7edb483effe2.gif)

* Note that when editing the viewconf, you have to change or remove the `uid` of the track when changing its type to ensure that it rerenders.

**Comment by pkerpedjiev** [comment]
Implemented in v1.10.0.

Take a look here: http://higlass.io/l/?d=Dakg-l1dTOycEp2_EgZs5A
