### ISSUE TITLE
Exported PNGs and SVGs have unwanted image smoothing applied

### ISSUE THREAD

**Issue by shaunmahony** [higlass/higlass#932]
_Commit_: 

Newbie to higlass here, so apologies if there's a simple fix. When I'm viewing a Hi-C .mcool file, and I export the view (PNG or SVG), the image I get doesn't match the view on screen. Specifically, it looks like the data has been smoothed or transformed in some way. 

#### Steps to reproduce
Using a custom installed instance of higlass. Problem occurs with both chrome and firefox on MacOS. 

#### Observed behavior
This is the image I get from the PNG export:
![image](https://user-images.githubusercontent.com/166420/84837534-617b8a00-b006-11ea-8d8b-f782e575c3c2.png)

#### Expected behavior
This is what I'm looking at on the screen:
![image](https://user-images.githubusercontent.com/166420/84837289-ba96ee00-b005-11ea-86ec-68e081a24c04.png)

As you can see, the PNG has both a tiling issue and some form of low res smoothing issue. I just want to export exactly what I see on the screen. What am I doing wrong?

**Comment by pkerpedjiev** [comment]
What version of HiGlass are you using and what operating system and browser?

When I try the same using the public deployment at http://higlass.io/l/?d=AbhpsuCMSq-hC2hVcqI3WQ the output looks nice and pixelated as expected 🤔

**Comment by sonnyarora** [comment]
Thanks Pete!

I'm in Dr. Mahony's lab supervising our instance of Higlass. We were loading the javascript for higlass in our own website according to the instructions here:

https://docs.higlass.io/javascript_api.html#overview

Looks like we were adding an older version (1.6.6) of Higlass and that was causing issues. Based on the version on the github page, I changed the javascript and css to 1.9.5 and this appears to be working to fix the smoothing issue.
