### ISSUE TITLE
Higlass series transformation does not work as expected

### ISSUE THREAD

**Issue by dmalzl** [higlass/higlass#933]
_Commit_: NA

#### Steps to reproduce
1. Generating mcool with cooler zoomify and balancing matrix with cooler balance and hicexplorer's hicCorrectMatrix KR implementation and saving the respective weights in new columns of the bins table named IC and KR. weights of nan bins are set to nan.

2. upload mcools to higlass instance on our cluster

#### Observed behavior
- The stored weights can be used to transform the shown values by right click -> samplename -> configure series -> transform -> weight_name. We have four samples, where for three of them there the transform tab show the options KR, Default and None (where I assume Default is IC?). However, the fourth has only ICE, Default and None to choose from although there is no ICE in the mcool (checked with cooler tree). Furthermore, all file trees look the same and balancing weight for both normalizations are available for all resolutions. We already deleted all files and reuploaded them but the problem is still there.

#### Expected behavior
- The expected behaviour would be that, if I have distinct balancing weights in my mcooler I would be able to choose them accordingly by name (Default = IC?) and it is definitely weird that only one of the matrices does not display the KR option but has ICE which is not even there

Do you have a clue whats going on here?

**Comment by pkerpedjiev** [comment]
Hey, we just released a new version of the docker container (v0.6.51). Would you mind giving it a try and seeing if this issue persists?

**Comment by dmalzl** [comment]
Hi, 

sorry for the long silence. I just tried it locally with the new docker container and the problem still persists. Having a little thought on this, maybe the column naming conflicts here with something. I use the names IC and KR for the two balancing results. I also found that KR is assumed as divisive (which probably is a projection of the cooler behaviour). Anyway, it still looks like this
![image](https://user-images.githubusercontent.com/52696584/87144822-a95d9c00-c2a8-11ea-8f06-ce30139f36ce.png)

**Comment by dmalzl** [comment]
I also tried to rename the weights now in the cooler from IC and KR to IC_weights and KR_weights but now I don't see any of them in the transforms. Do you have a hardcoded naming scheme of the weight columns that needs to be adopted. Because as far as I get if you name it any of the corrections juicer applies they are visible but any others are not so this is a bit suspicious.

**Comment by dmalzl** [comment]
I, for now, solved it by defaulting to name KR as weight and IC as ICE. This way the default is KR (don't worry the weights are multiplicative) and ICE can be chosen if one wants to.
