### ISSUE TITLE
setting 1D track range

### ISSUE THREAD

**Issue by faryabib** [higlass/higlass#946]
Hi,
I wonder if there is a way to set the range of 1D tracks. It is very helpful when comparing two conditions. Or, when the data has negative and positive values (e.g. PC1). 
Thanks - B

**Comment by pkerpedjiev** [comment]
There's a couple ways you can do that:

1. Lock value scales. This will ensure that two tracks always have the same maximum and minimum:

<img width="429" alt="image" src="https://user-images.githubusercontent.com/2143629/86172082-a9a0af00-bad2-11ea-851b-43cc279cfa2d.png">

2. If you'd like to see negative values, I recommend switching to the `horizontal-divergent-bar` track type:

<img width="679" alt="image" src="https://user-images.githubusercontent.com/2143629/86172132-bd4c1580-bad2-11ea-91c5-12cec4bc9400.png">

3. If all that fails, you can edit the viewconf and set the minimum and maximum values directly. Use the `valueScaleMin` and `valueScaleMax` options.

<img width="888" alt="image" src="https://user-images.githubusercontent.com/2143629/86172261-eff60e00-bad2-11ea-8705-e383e2c58457.png">

**Comment by sehilyi** [comment]
I am closing this issue because it looks to be addressed already.
