### ISSUE TITLE
RNA seq counts txt file

### ISSUE THREAD

**Issue by rahmas36** [higlass/higlass#951]
Hi, I've downloaded some RNA seq data from GEO. They are in a .counts.txt format. Can I convert this data into a format that is ingestible by HiGlass?

**Comment by pkerpedjiev** [comment]
Your best bet is to get into bigWig format and ingest that.

**Comment by rahmas36** [comment]
How would I convert from counts.text to bigwig? I have ingested RNA seq bigwig files before.

**Comment by pkerpedjiev** [comment]
You're better of asking that on https://bioinformatics.stackexchange.com/ or https://www.biostars.org/.

**Comment by rahmas36** [comment]
Thanks!

**Comment by pkerpedjiev** [comment]
I'd be curious what the procedure is as well. If you get an answer and have a moment, please do post an update here.

**Comment by golobor** [comment]
I think STAR can provide various coverage tracks in .bigWig format;
however, i'd recommend starting from .fastq files (shouldn't be too
difficult). Do check this pipeline, it may do what you need:
https://github.com/nf-core/rnaseq
