### ISSUE TITLE
Zooming in too far results in fractional genomic coordinates

### ISSUE THREAD

**Issue by ngehlenborg** [higlass/higlass#981]
An issue that we should fix is the ability to zoom into genomic sequences past 1 bp resolution, which results in fractional genomic coordinates, e.g. like here (https://higlass.io/l/?d=c1WqKNk1RWGzZyYePHW0ow):

<img width="1549" alt="image" src="https://user-images.githubusercontent.com/1216518/93332151-66133280-f7ef-11ea-80f8-71c7266b9cb6.png">

_Commit_: 

#### Steps to reproduce
1. Zoom in very, very far.

#### Observed behavior
- Genomic coordinates are displayed a fractions (below bp resolution).

#### Expected behavior
- No resolution lower than 1 bp should be allowed, no decimals for genomic coordinates.

**Comment by sehilyi** [comment]
#882 added a view option, `zoomLimits`, that limits the zoom level:

```json
"zoomLimits": [1, null] // highest zoom resolution is 1bp
```

This is, however, an optional config, so infinite zooming is supported by default.

Do you think we need to limit the zoom level to **1bp** by default?

**Comment by sehilyi** [comment]
Also, it looks axis labels still show decimals when zoomed in although `zoomLimits` is set to `[1, null]`. We would need to update `chromosome-labels` tracks not to show decimals.
