### ISSUE TITLE
slack badge in README.md is no longer rendering?..

### ISSUE THREAD

**Issue by golobor** [higlass/higlass#982]
_Commit_: 

#### Steps to reproduce
1. Open https://github.com/higlass/higlass in google chrome

#### Observed behavior
- The right-most badge for slack is not rendering

#### Expected behavior
- The right-most badge for slack is expected to render

I suspect that shields.io no longer supports slack, at least I couldn't find it in the badge directory.

**Comment by flekschas** [comment]
Thanks for reporting! Fixed the link and the badge
